feat: update meeting summary UI
ParabolInc/parabol pull request #10081
Opened 2024-08-06 16:52 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/10040

### To test

- [ ] Replace `wholeMeetingSummary` [here](https://github.com/ParabolInc/parabol/blob/0f98d26c304e749181adae271b99f6bfc567843f/packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx#L68) with dummy text that has markdown, e.g.: `The budget work is recognized for its future value in improving focus and communication within the team ([link](https://action.parabol.co/meet/twbP2qPXNK/discuss/3](https://action.parabol.co/meet/twbP2qPXNK/discuss/3) )).'`
- [ ] See that the link shows up as a formatted link

2024-08-08 20:10 UTC, Dschoordsch requested changes
Works, but I don't feel good merging it as is. At the very least we should sanitize it because I don't trust it. People might find a way to sneak html past ChatGPT somehow.

2024-08-08 20:10 UTC, Dschoordsch commented on packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
> +            <td style={textStyle} dangerouslySetInnerHTML={{__html: formattedSummary}} />
-1 We should sanitize the html as marked also [recommends](https://marked.js.org). We already use DOMPurify, so let's use it here as well.

2024-08-08 20:10 UTC, Dschoordsch commented on packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
> +  // replace links with styled links
-1 this is obvious, but instead we should explain why we do this instead of doing a cleaner approach so it serves as a warning not to copy this.

2024-08-12 17:41 UTC, mattkrick commented
look sanitary to me!

2024-08-12 17:41 UTC, mattkrick approved these changes

2024-08-12 17:43 UTC, merged