Fix prompt meeting bug
ParabolInc/parabol pull request #4236
Opened 2020-10-02 20:29 UTC by nickoferrall

This PR resolves 2 issues with template prompts:
1. If you remove a template prompt that is being used in an active/completed meeting, the meeting will crash
2. Removing a prompt removes that prompt from all completed meetings

It looks like bug causing the meeting to crash wasn't being caused by any of the 4 files discussed in #4222 but caused by the `handleRemoveReflectTemplatePrompt` file. 

This PR seems to resolve the two issues but I'm getting a pesky console error when removing a prompt which I'd like to resolve:

<img width="493" alt="console-err" src="https://user-images.githubusercontent.com/39854876/94965414-5ab04e80-04f3-11eb-9eae-b95dcf6998e0.png">

I'll keep working away at it but I wanted to share in case there's a clear solution I'm overlooking. 

I suspect the problem lies in the `handleRemoveReflectTemplatePrompt` file. Removing `prompts` from `selectedTemplate` does seem to be the right approach but perhaps I can grab `selectedTemplate` in a different way so it has the same `__typename`. I'll also keep digging to see where an id may not be unique.

2020-10-02 20:34 UTC, nickoferrall commented on packages/client/mutations/handlers/handleRemoveReflectTemplatePrompt.ts
> -  removeFromRefs(promptId, store, {ReflectTemplate: ['prompts']})
`removeFromRefs` was only being used in this file. After removing it here, I've deleted the file

2020-10-02 20:34 UTC, nickoferrall commented on packages/server/graphql/types/ReflectPhase.ts
> +            (!prompt.removedAt || meeting.createdAt < prompt.removedAt)
The logic only needs to be used here so I felt the custom dataLoader was probably overkill

2020-10-02 20:34 UTC, nickoferrall commented on packages/client/mutations/RemoveReflectTemplatePromptMutation.ts
> -    optimisticUpdater: (store) => {
This `optimisticUpdater` was causing a console err of a store update within a store update. After removing it, I've tested removing a prompt on a 3G network and there doesn't seem to be any difference in the responsiveness

2020-10-07 17:26 UTC, nickoferrall commented
Hey @tiffanyhan, to lighten the load on Matt's shoulders, it'd be great if you could review this PR when you get the chance

2020-10-07 19:44 UTC, tiffanyhan requested changes
Hey @nickoferrall 

Followed the steps in the AC, and created a meeting with a team template. In a second window, I deleted that template. The active meeting's "reflect" phase then becomes blank, and the facilitator is unable to navigate further. Lmk if you can reproduce it on your side.

<img width="1064" alt="Screen Shot 2020-10-07 at 12 39 33 PM" src="https://user-images.githubusercontent.com/11562889/95379909-d8c97800-089a-11eb-9862-1da9ba59a24a.png">

2020-10-08 09:18 UTC, nickoferrall commented
@tiffanyhan interesting! I haven't been able to repro that one. To clarify, you get that bug when removing a template prompt or a template? This PR is only focused on fixing the template prompt bugs. 

I've recorded a quick Loom to share with you what I see on my end:
https://www.loom.com/share/4b4a0c32a5184e28b5e2ec7ce7d5ca58

If the error persists for you, it'd be great to get more info on how I can repro it.

2020-10-08 18:33 UTC, tiffanyhan commented
@nickoferrall you are totally right. i misread the AC and was removing the entire template rather than a reflect prompt. now it is behaving as expected. the migrations and code looks good to me too. nice work on this!

2020-10-08 18:33 UTC, tiffanyhan approved these changes

2020-10-08 18:33 UTC, merged