Check-in agenda state
ParabolInc/parabol pull request #4242
Opened 2020-10-06 06:29 UTC by NikAiyer

This PR attempts to solve the following issue: #4240 

If there are no stages present on the current phase, the onClick handler in AgendaItem gets returned with a undefined value, and the completion status gets set to false. Because the other phases do not have stages, when the user is on any other phase, clicking on agenda items becomes disabled and the items themselves are not shown as complete. In order to access the agenda items, you must click on Team Agenda first.

This PR fixes this issue by doing the following:
* adds phases variable to keep track of all phases in meeting, as well as the stages for agendaitems
* uses the stages from the agendaitems phase whenever the current phase is not agendaitems

Users can:

*   add new agenda item at Last Call, and navigate to it
*   see correct agenda item completion state

2020-10-08 19:37 UTC, mattkrick commented
adding @nickoferrall to test

2020-10-12 14:31 UTC, nickoferrall requested changes
Nice work tracking down and then solving this nasty looking bug. Small changes requested and then it looks good to go

2020-10-12 14:31 UTC, nickoferrall commented on packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
> +  const agendaItemsPhase = phases!.find(
Looks like we don't need both `!` here, we can just use `phases.find(...`

2020-10-12 14:31 UTC, nickoferrall commented on packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
> +        ...AgendaItemAllMeetingPhases @relay(mask: false)
We could pass in `...AgendaItemPhase` instead here and then we'd be able to remove `...AgendaItemAllMeetingPhases` from the file

2020-10-13 08:54 UTC, nickoferrall approved these changes
LGTM!

2020-10-13 08:54 UTC, merged