Sprint poker template UI (minus scale UI)
ParabolInc/parabol pull request #4310
Opened 2020-11-04 18:18 UTC by tianrunhe

Issue: #4057 

This PR implements UI for sprint poker template minus the scale UI part.

Tests:

- [ ] Add a new poker template
- [ ] Clone a poker template
- [ ] Rename a poker template
- [ ] Delete a poker template
- [ ] Change the scope of a poker template
- [ ] Add a new dimension
- [ ] Rename a dimension
- [ ] Delete a dimension
- [ ] Drag and move a dimension
- [ ] Select a scale for a dimension

2020-11-04 18:31 UTC, tianrunhe commented
@ackernaut Hey Terry, would love to have your first pass review before I send it to Matt. Thanks in advance!

2020-11-04 22:27 UTC, ackernaut commented
@tianrunhe will do, thanks for pinging!

2020-11-05 17:32 UTC, ackernaut commented
### Test no. 1
- [x] Add a new poker template
- [ ] Clone a poker template
- [ ] Rename a poker template
- [ ] Delete a poker template
- [ ] Change the scope of a poker template
- [ ] Add a new dimension
- [ ] Rename a dimension
- [ ] Delete a dimension
- [ ] Drag and move a dimension
- [ ] Select a scale for a dimension

2020-11-05 19:25 UTC, ackernaut requested changes
Nice work, Bruce!! Thanks for the complete checklist. The UI is working well. For some reason, I’m seeing duplicate scale items in the public template (see screenshot). Also, I pushed a small change to how those hanging components are positioned on template items as I noticed small nuances in how we were laying out icons etc. Once you figure out the duplicate scale items, I’d say it’s ready for code review.
![Screen Shot 2020-11-05 at 13 06 28](https://user-images.githubusercontent.com/307286/98286817-2bfe1b80-1f6a-11eb-9fce-c036674ee138.png)

2020-11-05 19:43 UTC, tianrunhe commented
@ackernaut Thanks for the review! A quick fix was just pushed, please verify :smiley:

2020-11-05 20:20 UTC, ackernaut commented
@tianrunhe that change worked for me! I noticed that when I open the scale menu some selected options are already highlighted and others aren’t. See here:

![2020-11-05 14 16 43](https://user-images.githubusercontent.com/307286/98292158-e5142400-1f71-11eb-8d00-202c50cb6c92.gif)

2020-11-05 20:20 UTC, ackernaut approved these changes

2020-11-05 21:42 UTC, tianrunhe commented
> @tianrunhe that change worked for me! I noticed that when I open the scale menu some selected options are already highlighted and others aren’t. See here:
> 
> ![2020-11-05 14 16 43](https://user-images.githubusercontent.com/307286/98292158-e5142400-1f71-11eb-8d00-202c50cb6c92.gif)

That's an interesting find! I wonder if that's an existing implicit bug in our `Menu` implementation. The symptom is that you got to have a `DropdownMenuLabel` component inside the `Menu` component, in order for the indices work. Otherwise, like in this case, the active indices will be correct except for the very first one. I'll talk with Matt on this one.

2020-11-11 20:28 UTC, mattkrick requested changes

2020-11-11 20:28 UTC, mattkrick commented on packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
> +      errorTimerId.current = window.setTimeout(() => {
this is a really nice touch!
what do you think about refactoring this logic into `useMutationProps`?
API could be `onError(error: Error, removeAfter: number)`

2020-11-11 20:28 UTC, mattkrick commented on packages/client/modules/meeting/components/AddPokerTemplateDimension.tsx
> +class AddPokerTemplateDimension extends Component<Props> {
nit: can you write this as a functional component?
we deprecated class-based components back in 2018 & have been slowly trying to get them out of the app. Once they're gone we can get rid of a lot of class-only helpers like `withAtmosphere` so we can keep our codebase as small as possible

2020-11-11 20:28 UTC, mattkrick commented on packages/client/modules/meeting/components/EditableTemplateDimension.tsx
> +class EditableTemplateDimension extends Component<Props> {
functional component, if possible

2020-11-16 18:03 UTC, mattkrick commented on packages/client/modules/meeting/components/AddPokerTemplateDimension.tsx
>  export default createFragmentContainer(withMutationProps(withAtmosphere(AddPokerTemplateDimension)), {
ah, for the refactor can you repace the HOCs with hooks? 
e.g. get rid of `withAtmosphere` and add `useAtmosphere`

2020-11-16 23:13 UTC, mattkrick commented
CR complete! going through the UI:
- [ ] for disabled scale dropdowns, at a minimum we need to have `cursor: disabled`, i kept clicking it wondering why it wasn't dropping down. additionally, we could remove the down arrow icon, or make the text a little more gray. @ackernaut 
- [ ] for retros, the public templates that don't have illustrations show nothing (I think this is a bug). For poker, the ones that don't have illustrations show the default picture. they should act the same

2020-11-17 16:43 UTC, merged

2020-11-17 16:43 UTC, mattkrick commented
🎉  nice work!