Template editor FAB changes
ParabolInc/parabol pull request #4439
Opened 2020-12-14 21:31 UTC by tianrunhe

Resolves #4128 

Tests:

- [ ] The top list item is a control, `Create New Template`. This control is hidden when there’s a template called ‘*New Template’.
- [ ] The floating button ‘Use Template’ is an explicit control to use the selected template for the meeting. 
- [ ] If folks navigate to other templates (e.g. just browsing) but close the dialog instead of tapping the Use Template button, the template selection doesn’t change.
- [ ] Creating a new template & cloning a template should select the active template
- [ ] Removing a template should activate the next available template

2020-12-14 21:46 UTC, tianrunhe commented
@ackernaut Ready for UI/UX tests. Thanks!

2020-12-15 20:44 UTC, ackernaut commented
### Test cycle no. 1

- [ ] The top list item is a control, `Create New Template`. This control is hidden when there’s a template called ‘*New Template’.
- [ ] The floating button ‘Use Template’ is an explicit control to use the selected template for the meeting. 
- [ ] If folks navigate to other templates (e.g. just browsing) but close the dialog instead of tapping the Use Template button, the template selection doesn’t change.
- [ ] Creating a new template & cloning a template should select the active template
- [ ] Removing a template should activate the next available template

2020-12-15 23:29 UTC, ackernaut approved these changes
Hey @tianrunhe this looks good! Thanks for knocking it out so quickly. A few things to consider at your discretion:
- I pushed a change to the new and select controls, feel free to push back. I think the hanging icon of the new template control doesn’t work by itself in a list and the select button was too large when the template had many components
- When I close the dialog while browsing to another template, but without selecting it, and then open it again it’s still on that other template and my instinct was that the selected template should load when I open the dialog again — low tension, no need for change if you don’t want

2020-12-16 00:29 UTC, tianrunhe commented
@ackernaut 
> * I pushed a change to the new and select controls, feel free to push back. I think the hanging icon of the new template control doesn’t work by itself in a list and the select button was too large when the template had many components

Looking great!

> * When I close the dialog while browsing to another template, but without selecting it, and then open it again it’s still on that other template and my instinct was that the selected template should load when I open the dialog again — low tension, no need for change if you don’t want

I fixed this. Simple changes.

2020-12-16 00:29 UTC, tianrunhe commented
@mattkrick Ready for code review. Thanks!

2020-12-21 22:03 UTC, mattkrick requested changes
CR complete! all pretty minor stuff, fantastic work!

2020-12-21 22:03 UTC, mattkrick commented on packages/client/modules/meeting/components/SelectTemplate.tsx
> +  const errorTimerId = useRef<undefined | number>()
when does this get set?

2020-12-21 22:03 UTC, mattkrick commented on packages/client/utils/relay/setTemplateId.ts
> +const setTemplateId = (atmosphere: Atmosphere, teamId: string, templateId: string | null, meetingType: MeetingTypeEnum) => {
nit: lets rename this to show it's changing the active template.
maybe `activateTemplate` or `setActiveTemplate`?

2020-12-21 22:03 UTC, mattkrick commented on packages/client/hooks/useSelectTopTemplate.ts
> +const useSelectTopTemplate = (edges: readonly {node: {id: string}}[], selectedTemplateId: string, teamId: string, isActive: boolean, meetingType: MeetingTypeEnum) => {
lets rename this since we're changing the active template & not the selected one.
maybe `useActivateTopTemplate`?

2020-12-21 22:40 UTC, tianrunhe commented on packages/client/modules/meeting/components/PokerTemplatePicker.tsx
> +      setTemplateId(atmosphere, teamId, selectedTemplate.id, MeetingTypeEnum.poker)
This is to address Terry's feedback:

> When I close the dialog while browsing to another template, but without selecting it, and then open it again it’s still on that other template and my instinct was that the selected template should load when I open the dialog again

But I guess setting the activeTemplate to be the selectedTemplate on portal mount fixes this. Will remove this piece.

2020-12-23 22:20 UTC, mattkrick commented
Oh gosh this is so darn good!
Just a couple changes to the UI:
- if selected template === active template, the "Select Template" button should be hidden. that way, it is hidden when they open the modal. that means when they click another template, it will appear (bonus points for animating the opacity) & draw their attention to it.
- the "Select Template" FAB should be floating in the bottom right (maybe right: 16, bottom: 16) instead of just being at the bottom of the list. to reproduce, check out the FAB position on a template with only 1 or 2 prompts. it's much higher up
-  IMO, "Create new template" doesn't belong on the org or public tabs, it should only be on the team tabs, but if you feel strongly otherwise I'm OK with leaving it

2020-12-23 22:38 UTC, ackernaut commented
>if selected template === active template, the "Select Template" button should be hidden. that way, it is hidden when they open the modal. that means when they click another template, it will appear (bonus points for animating the opacity) & draw their attention to it.

+1, a nice touch

>the "Select Template" FAB should be floating in the bottom right (maybe right: 16, bottom: 16) instead of just being at the bottom of the list. to reproduce, check out the FAB position on a template with only 1 or 2 prompts. it's much higher up

I do like the floating aspect of it. Perhaps we need to ensure some minimal bottom gutter so controls (e.g. sharing settings) can be scrolled out from under fully?

>IMO, "Create new template" doesn't belong on the org or public tabs, it should only be on the team tabs, but if you feel strongly otherwise I'm OK with leaving it

I agree with the pure logic. However, TMK folks start off on the Public tab and it may not be apparent where to create a new template. Maybe if they want it bad enough they’ll find it? I wonder if folks would start cloning templates just to get their own template and have to totally overhaul the cloned template to get to their end goal (assuming they don’t look on the Team tab, which honestly, might not be apparent)?

2021-01-05 00:40 UTC, tianrunhe commented
I updated the button appear/disappear piece and left the rest untouched. Let me know if that looks good! @mattkrick

2021-01-05 16:31 UTC, mattkrick commented on packages/client/modules/meeting/components/SelectTemplate.tsx
> +  WebkitAnimation: `${fadein} 2s`
emotion does vendor prefixes for us automatically! no webkit needed

2021-01-07 18:30 UTC, mattkrick commented
This is gonna make a lot of first time users VERY happy. fantastic work!

2021-01-07 18:30 UTC, merged