Fix collapsed reflections
ParabolInc/parabol pull request #5642
Opened 2021-11-10 13:12 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/5623

2021-11-10 15:29 UTC, nickoferrall commented
Hey @BartoszJarocki, I pestered you with my last CR request, but as this is touching the `drag.ref` logic in `DraggableReflectionCard`, this PR might be relevant for your work. Mind giving it a review?

2021-11-11 09:33 UTC, Dschoordsch requested changes
I tested it and it worked.

2021-11-11 19:04 UTC, nickoferrall commented
Thanks for the proactive review @Dschoordsch! Change pushed - moving to Maintainer Review

2021-11-11 20:19 UTC, Dschoordsch approved these changes

2021-11-12 20:59 UTC, mattkrick commented
LGTM

2021-11-12 20:59 UTC, merged