Added set new team lead mutation to internal schema
ParabolInc/parabol pull request #5658
Opened 2021-11-16 15:35 UTC by BartoszJarocki

Related discussion: https://parabol.slack.com/archives/C4JAUUZ9P/p1637070049068200

I couldn't reuse or adjust `promoteToTeamLead` as it's running in the context of the logged-in user. So now we have something with interface sales folks can use with ease ie. arguments are team id and new team lead email. 

```
mutation {
	setNewTeamLead(teamId: "8yrFHNhdER", newTeamLeadEmail: "bartosz@parabol.co")	
}
```

2021-11-16 15:36 UTC, BartoszJarocki commented
@Dschoordsch do you mind taking a look? Thanks!

2021-11-17 13:14 UTC, Dschoordsch requested changes

2021-11-17 13:14 UTC, Dschoordsch commented on packages/server/graphql/intranetSchema/mutations/setNewTeamLead.ts
> +      .run()
We should run both rethink changes at once:
```
const {newLead} = await Promise.all(r({
  downgradeOld: r
      .table('TeamMember')
      .filter({teamId, isLead: true})
      .update({
        isLead: false
      }),
  newLead: r
      .table('TeamMember')
      .filter({email: newTeamLeadEmail, teamId})
      .update({
        isLead: true
      })
   }).run())
```

2021-11-17 13:14 UTC, Dschoordsch commented on packages/server/graphql/intranetSchema/mutations/setNewTeamLead.ts
> +      type: GraphQLNonNull(GraphQLID),
please use `new GraphQLNonNull(...)` from now in preparation of graphql v16, see #5662

2021-11-17 13:14 UTC, Dschoordsch commented on packages/server/graphql/intranetSchema/mutations/setNewTeamLead.ts
> +      type: GraphQLNonNull(GraphQLEmailType),
please use `new GraphQLNonNull(...)`

2021-11-17 13:14 UTC, Dschoordsch commented on packages/server/graphql/intranetSchema/mutations/setNewTeamLead.ts
> +    _source,
please add type `_source: unknown`. `unknown` is a safe type for unused variables because it doesn't allow you to do anything with it

2021-11-18 06:32 UTC, BartoszJarocki commented
@Dschoordsch thank you for the review! I fixed all the feedback, would you mind double checking? thank you!

2021-11-18 06:57 UTC, Dschoordsch approved these changes
I tested it and it looks good.

2021-11-18 17:25 UTC, mattkrick commented
> I couldn't reuse or adjust promoteToTeamLead as it's running in the context of the logged-in user.

In efforts to keep a nice tight API I'd suggest we just change the permissions at the top of the `promoteToTeamLead`. I added a commit as an example, i'm totally fine with changing the input args, I just want to make sure we don't have 2 mutations doing the same thing

2021-11-19 06:42 UTC, BartoszJarocki commented
@mattkrick got it. The reason I've done it that way is I didn't really want to change the public-facing interface to fit our internal needs. If that's not a problem, then great. Thank you for the example! I pushed the changed params, aligned the frontend (and added a little bit more typing along the way) so please let me know if it looks ok to you now, thank you!

2021-11-24 00:33 UTC, mattkrick commented
looks great!
i'm all about shrinking code surface area vs. changes to the code. fewer places for bugs to creep in is always a win.

2021-11-24 00:33 UTC, merged