Fix husky hooks
ParabolInc/parabol pull request #5702
Opened 2021-11-23 09:04 UTC by igorlesnenko

2021-11-23 14:08 UTC, BartoszJarocki commented
@igorlesnenko unfortunately `eslint` doesn't work still on my end. 
```
~/Work/parabol/web-parabol fix-husky*
❯ yarn lint
yarn run v1.22.15
$ lerna run --parallel lint
lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "yarn run lint"
parabol-client: $ eslint --fix ./**/*.{ts,tsx}
parabol-server: $ eslint --fix ./**/*.ts
parabol-server: Oops! Something went wrong! :(
parabol-server: ESLint: 8.2.0
parabol-server: ESLint couldn't find the plugin "eslint-plugin-prettier".
parabol-server: (The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "/Users/bartoszjarocki/Work/parabol/web-parabol".)
parabol-server: It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
parabol-server:     npm install eslint-plugin-prettier@latest --save-dev
parabol-server: The plugin "eslint-plugin-prettier" was referenced from the config file in "../../.eslintrc.js".
parabol-server: If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
parabol-server: error Command failed with exit code 2.
parabol-server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run lint exited 2 in 'parabol-server'
lerna ERR! yarn run lint stdout:
$ eslint --fix ./**/*.ts
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run lint stderr:

Oops! Something went wrong! :(

ESLint: 8.2.0

ESLint couldn't find the plugin "eslint-plugin-prettier".

(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "/Users/bartoszjarocki/Work/parabol/web-parabol".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-prettier@latest --save-dev

The plugin "eslint-plugin-prettier" was referenced from the config file in "../../.eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
lerna ERR! yarn run lint exited 2 in 'parabol-server'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

It starts to work when I add `--resolve-plugins-relative-to .` to `lint` command in package.json.

2021-11-24 14:04 UTC, Dschoordsch requested changes

2021-11-24 14:10 UTC, igorlesnenko commented on package.json
> +    "pre-commit": "lerna run --concurrency 1 --stream precommit",
Made `precommit` everywhere as I've seen this script name in three different packages.

2021-11-24 14:10 UTC, igorlesnenko commented on package.json
> +    "pre-commit": "lerna run --concurrency 1 --stream precommit",
Removed `--concurrency 1`

2021-11-24 15:00 UTC, Dschoordsch approved these changes

2021-11-30 00:13 UTC, merged