Add updatedAt trigger to User table
ParabolInc/parabol pull request #5733
Opened 2021-12-01 15:31 UTC by Dschoordsch

Relates-To: #5723 
Resolves: #5384

2021-12-02 18:43 UTC, tianrunhe requested changes
Where do those generated changes come from? You don't seem to edit any SQL files?

2021-12-02 18:43 UTC, tianrunhe commented on packages/server/postgres/migrations/1638368905980_userUpdatedAtTrigger.ts
> +  pgm.sql(`
We should use:

```javascript
  const client = new Client(getPgConfig())
  await client.connect()
  await client.query(`
    ...
  `)
  await client.end()
```

2021-12-03 12:23 UTC, Dschoordsch commented
The `domain` changes were artefacts from #5719

2021-12-03 23:50 UTC, tianrunhe approved these changes

2021-12-10 15:55 UTC, merged