Spotlight height doesn't change when searching
ParabolInc/parabol pull request #5747
Opened 2021-12-06 18:48 UTC by nickoferrall

Fix #5739 

This PR also renames `SpotlightGroups` to `SpotlightResults` to improve naming consistency.

2021-12-06 19:05 UTC, nickoferrall commented on packages/client/hooks/useResultsHeight.ts
> +    if (resultsRef.current) {
If there's no `resultsRef`, e.g. when we're showing the empty state, the height was being set to `100%` but not being recalculated in `useLayoutEffect` as `newHeight` was `undefined`

2021-12-06 19:05 UTC, nickoferrall commented on packages/client/components/SpotlightResults.tsx
> +        <SpotlightResultsEmptyState height={scrollHeight} />
EmptyState needs to inherit the padding in `ResultsWrapper`. There's a few different ways we could do this, and I don't love the ternary operator within the JSX, but I prefer this DRY approach vs copying padding to empty state component, two result statements wrapped in the same `ResultsWrapper`, or adding it to the parent component that doesn't contain any styles.

2021-12-06 19:06 UTC, nickoferrall commented
Hey @igorlesnenko, could you review this one, please?

2021-12-07 14:04 UTC, igorlesnenko requested changes
I still see some height change on my side:

https://user-images.githubusercontent.com/466991/145042147-6447d2da-ea04-4f32-b65d-cc89d56db10e.mov

2021-12-08 11:01 UTC, nickoferrall commented
Thanks, @igorlesnenko! I've pushed an update. It's ready when you are

2021-12-09 10:27 UTC, igorlesnenko approved these changes
Looks good to me

2021-12-10 16:23 UTC, merged