add redis-commander to dev docker-compose
ParabolInc/parabol pull request #5816
Opened 2021-12-20 23:10 UTC by mattkrick

sometimes it's nice to have redis commander 🤷

2021-12-22 15:12 UTC, Dschoordsch requested changes

2021-12-22 15:12 UTC, Dschoordsch commented on docker/dev.yml
> +      - "8082:8081"
-1 networks is missing
```
    networks:
      - parabol-network
```

2022-01-11 09:29 UTC, Dschoordsch commented on docker/dev.yml
> +      - "8082:8081"
Added it myself since PR is stale.

2022-01-11 09:29 UTC, Dschoordsch approved these changes

2022-01-11 14:13 UTC, BartoszJarocki approved these changes
👌🏻

2022-01-11 14:15 UTC, merged