add strict eq eslint rule
ParabolInc/parabol pull request #5848
Opened 2022-01-07 20:37 UTC by tiffanyhan

Resolve: #5823

**AC**
- [ ] strict eq enforced by linter

2022-01-07 20:39 UTC, tiffanyhan commented
@tianrunhe can you take a look at this one please?

2022-01-10 18:29 UTC, tianrunhe requested changes
Looks like it only applies to `/server`, not `/client`? e.g., [here](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/utils/AtlassianManager.ts#L382) it's still just `==`.

2022-01-10 20:12 UTC, tiffanyhan commented
> Looks like it only applies to `/server`, not `/client`? e.g., [here](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/utils/AtlassianManager.ts#L382) it's still just `==`.

ah thanks for catching! looks like we have a number of eslint problems that are causing the command to exit early. i'll triage

2022-01-13 19:55 UTC, tiffanyhan commented on packages/client/.eslintrc.js
>    parserOptions: {
look like https://github.com/ParabolInc/parabol/commit/a4963401 broke the client lint command. i get lots of `Definition for rule was not found` errors. reverting to the earlier plugins fixes the issue, but it means we're no longer supporting eslint v7+.

2022-01-13 19:56 UTC, tiffanyhan commented on packages/client/.eslintignore
> +serviceWorker/*
`.eslintignore` in root of parabol project dir was not working, so i broke it out into separate client and server files and put them in the root of their respective packages.

2022-01-13 19:56 UTC, tiffanyhan commented on packages/server/.eslintignore
> +postgres/migrationTemplate.ts
`.eslintignore` in root of parabol project dir was not working, so i broke it out into separate client and server files and put them in the root of their respective packages.

2022-01-13 19:58 UTC, tiffanyhan commented on packages/client/tsconfig.eslint.json
> +}
was getting tons of `The file does not match your project config` errors. this file fixes it.

2022-01-13 20:00 UTC, tiffanyhan commented on packages/client/components/StandardHubUserMenu.tsx
> +interface Props extends RouteComponentProps<{[x: string]: string | undefined}> {
went ahead and fixed "Don't use `{}` as a type" errors

2022-01-13 20:01 UTC, tiffanyhan commented on packages/client/hooks/useAutoCheckIn.ts
> +        {onCompleted: subscribeToMeeting, onError: () => undefined}
went ahead and fixed no-empty-function errors

2022-01-13 20:02 UTC, tiffanyhan commented on packages/client/.eslintrc.js
>    parserOptions: {
if this change is accepted, we should create a separate issue for supporting eslint v7+ in client package?

2022-01-13 20:05 UTC, tiffanyhan commented on .eslintrc.js
> +    '@typescript-eslint/ban-ts-comment': 'off',
["ban-ts-comment" is the correct rule name](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#2180-2020-01-27) for later versions of `typescript-eslint`

2022-01-13 20:18 UTC, tiffanyhan commented
Good news: we can run `yarn lint` successfully now, without the command exiting early bc of problems with client linting.

Bad news: there are still a few (2-3 instances) of loose equality that's not being detected by eslint. E.g. [movePokerTemplateScaleValue.ts](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/server/graphql/mutations/movePokerTemplateScaleValue.ts#L54), [Bug.ts](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/utils/screenBugs/Bug.ts#L77), [PhaseItemEditor](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx#L89). I'm pretty certain these files should be in the dependency graph and detected by eslint based on [client/tsconfig.esilnt.json](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/tsconfig.eslint.json#L0-L1). I don't know why the files aren't being picked up. I tested adding other errors in the files that eslint should complain about, with the same result. So it's not detecting the file at all.

Since these files not being detected is a general eslinting problem and not specific to adding the strict eq rule, I propose we should create a separate issue for it so it needn't block this PR.

2022-01-13 20:31 UTC, tiffanyhan commented on packages/client/.eslintrc.js
> +  // plugins: ['@typescript-eslint', 'prettier'], // revert a4963401
look like a496340 broke the client lint command. i get lots of Definition for rule was not found errors. reverting to the earlier plugins fixes the issue, but i suppose it means we’re no longer supporting eslint v7+.

if this change is accepted, we should create a separate issue for supporting eslint v7+ in client package?

2022-01-13 20:40 UTC, tiffanyhan commented
Good news: we can run `yarn lint` successfully now, without the command exiting early bc of problems with client linting.

Bad news: there are still a few (2-3 instances) of loose equality that’s not being detected by eslint. E.g. [movePokerTemplateScaleValue.ts](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/server/graphql/mutations/movePokerTemplateScaleValue.ts#L54), [Bug.ts](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/utils/screenBugs/Bug.ts#L77), [PhaseItemEditor](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx#L89). I’m pretty certain these files should be in the dependency graph and detected by eslint based on [client/tsconfig.esilnt.json](https://github.com/ParabolInc/parabol/blob/strict-eq/packages/client/tsconfig.eslint.json#L0-L1). I don’t know why the files aren’t being picked up. I tested adding other errors in the files that eslint should complain about, with the same result. So it’s not detecting the file at all.

Since these files not being detected is a general eslinting problem and not specific to adding the strict eq rule, I propose we should create a separate issue for it so it needn’t block this PR.

2022-01-25 19:09 UTC, mattkrick commented
This highlights an error I found in how we call eslint-- https://github.com/ParabolInc/parabol/issues/5952
The ignore file also doesn't work because we need to pass in a flag on where to find it e.g. `--ignore-file ../../.eslintignore` via CLI. 

All that said, this PR moves us ahead a little bit, so we'll merge this & then we can tackle how we ignore files after we fix https://github.com/ParabolInc/parabol/issues/5952

2022-01-26 10:16 UTC, igorlesnenko commented
Yeah, looks like #5952 is also the reason why eslint is not picking some files. 
It does not pick files nested deeper than the second level: https://stackoverflow.com/questions/54165756/eslint-glob-is-not-considering-all-directories-recursively

2022-01-26 10:17 UTC, igorlesnenko approved these changes

2022-01-27 15:44 UTC, mattkrick commented
progress! i'll see if i can carve off the server to fix the pattern & we can make some more progress there

2022-01-27 15:44 UTC, merged