Add code review policy
ParabolInc/parabol pull request #5855
Opened 2022-01-11 09:21 UTC by Dschoordsch

2022-01-11 14:17 UTC, Dschoordsch commented on docs/codeReview.md
> +    - refactor? ie. the author's doing things in a part of the code that could be improved (for example changing from fragment containers to relay hooks). Then it’s the author’s responsibility to mak
It's not official yet, but you're right, I tried to incorporate this in line 16. If you're fine with it I would remove this bullet point

2022-01-11 14:19 UTC, BartoszJarocki commented on docs/codeReview.md
> +    - refactor? ie. the author's doing things in a part of the code that could be improved (for example changing from fragment containers to relay hooks). Then it’s the author’s responsibility to mak
sure, it turned out numbers work great for us so let's get rid of this part. really good idea to have it here!

2022-01-11 15:41 UTC, BartoszJarocki approved these changes

2022-01-11 17:40 UTC, nickoferrall approved these changes
LGTM! Thanks for writing this up

2022-01-11 17:40 UTC, nickoferrall commented on docs/codeReview.md
> +      - lowest score +1? the PR goes back to self-review
+1 I'd avoid using the word score as it implies the numbers are being summed. Perhaps, "if there are no -2 or -1 comments, but there are +1 comments, the PR goes back to self-review"?

On the line below, we could say "if there are no comments or only +2 comments, the PR gets merged"?

2022-01-11 21:41 UTC, enriquesanchez commented on docs/codeReview.md
> +The goal is to help reviewers to make their intentions clear to the author and for the author to know exactly what is expected of to pass the next review round.
`...what is expected of to pass...`

Should it say instead "what is expected of _them_ to pass"?

2022-01-11 22:16 UTC, tianrunhe requested changes

2022-01-11 22:16 UTC, tianrunhe commented on docs/codeReview.md
> +    - Changes requested? Move ticket to self-review
\-1 Can we be clear here that by "ticket" we mean the issue this PR is corresponding to.

2022-01-11 22:16 UTC, tianrunhe commented on docs/codeReview.md
> +    - Approved? Move to maintainer-review
\-1 "Move the issue to maintainer-review"

2022-01-11 22:19 UTC, tianrunhe commented
The policy looks good for us internally. My request is more on behalf of external users: let's make it more explicit for some terms we use here.

2022-01-12 18:56 UTC, tianrunhe approved these changes
Great work! Thanks for creating this policy!

2022-01-12 22:56 UTC, mattkrick commented
love it! we need this to live in github for external PR contributions. in the future, we will move governance to its own github repo, but that's a future problem & this does a good job of building the case for moving our governance from notion to GH.

2022-01-12 22:57 UTC, mattkrick approved these changes

2022-01-13 16:26 UTC, enriquesanchez approved these changes

2022-01-13 17:13 UTC, mattkrick commented
that's a whole lot of green checkmarks. merging!

2022-01-13 17:13 UTC, merged