Implement choosing random person as facilitator
ParabolInc/parabol pull request #5857
Opened 2022-01-11 19:18 UTC by tianrunhe

Implements #5531 .

Notice the implementation is a little bit different than the issue description as I feel like this is a less intrusive change that's safe to try: no new visual changes, just adding one more item to the existing menu.

![](https://user-images.githubusercontent.com/1879975/149007122-028761ee-de64-4f02-8602-5b5cd5ef828c.png)

2022-01-11 19:40 UTC, tianrunhe commented
@enriquesanchez Wanna take a look? Especially let me know if you have better idea on the wording...

2022-01-11 21:53 UTC, enriquesanchez requested changes
Oh! This is nice!

I like that the action is under the `...` menu, this way it doesn't take up any additional space and it's out of the way for those scenarios where the facilitator is already assigned.

I wouldn't change the current wording for `Take the facilitator role`, I'd leave that alone.

As for the new action, I think something like "Randomize facilitator" would be better? How does that sound?

2022-01-11 23:55 UTC, enriquesanchez approved these changes
LGTM! 👍

2022-01-12 01:23 UTC, tianrunhe commented
Hey @igorlesnenko , can you take a look? Thanks!

2022-01-14 19:18 UTC, igorlesnenko approved these changes
Looks good!

2022-01-19 20:45 UTC, mattkrick commented
fix #5531

2022-01-19 22:21 UTC, mattkrick requested changes

2022-01-19 22:21 UTC, mattkrick commented on packages/client/components/FacilitatorMenu.tsx
> +        userId
-1 this will promote a potentially offline meeting member
let's filter by `user.isConnected`

2022-01-19 22:21 UTC, mattkrick commented on packages/client/components/Facilitator.tsx
> +        userId
```gql
user {
  isConnected
}
```

2022-01-20 21:09 UTC, mattkrick commented
perfect!

2022-01-20 21:09 UTC, merged