Add string filtering to team / team member filter dropdowns
ParabolInc/parabol pull request #5945
Opened 2022-01-25 05:23 UTC by jmtaber129

fixes https://github.com/ParabolInc/parabol/issues/5777.

(still a bit of a work in progress)

2022-01-27 16:20 UTC, Dschoordsch commented on packages/client/components/UserDashTeamMenu.tsx
> +  } = useSearchFilter(filteredTeams!, (team) => team.name)
-1 please remove `!`

2022-01-27 17:35 UTC, jmtaber129 commented
Added a "No results" placeholder for when a search query is present, but there are no results.

Fixed those bugs - the `getValue` methods were returning non-lower-case strings, so it was matching a lower-case query to mixed case strings.  Fixed this by calling `toLowerCase()` on the result of `getValue` in the `useSearchFilter` hook

2022-01-27 18:55 UTC, Dschoordsch approved these changes
Works now. I have just one comment you don't need to address. I will move this forward to maintainer review. Good work!

2022-01-27 18:55 UTC, Dschoordsch commented on packages/client/components/UserDashTeamMemberMenu.tsx
> +const NoResults = styled(MenuItemLabel)({
+1 You could put this component in a separate file as well and reuse it.

2022-01-28 03:03 UTC, mattkrick commented
This'll be my top PR to review tomorrow

2022-01-28 18:48 UTC, mattkrick commented
Code looks super clean! Great abstraction using the hook & refactoring all the similar components.

Issue 1:
- Search box appears when there is only 1 person on the team. Maybe hide the search box if the total results are < 6. Business logic is up to you, share your thoughts. 
![Screen Shot 2022-01-28 at 10 27 24 AM](https://user-images.githubusercontent.com/5514175/151603886-5fd1cea1-ae76-42e7-98b9-9fa54cee013c.png)


Issue 2:
- The active value appears in the search results. Was this intended? With the existing logic, if "Matt" is the current assignee, then "Matt" is removed from the results (1 fewer thing to scroll). No strong opinion on this, but want to get your thoughts

Issue 3:
- Clicking a team member when scrollTop > 0 doesn't work (at least i _think_ that's what's going on?) repro here:

https://user-images.githubusercontent.com/5514175/151603971-be92c350-5668-4b27-b8b0-163b38b0ff24.mov

2022-01-28 18:57 UTC, mattkrick requested changes
-1 little usability bug with clicking in the mid or bottom of the scroll container. I agree with Georg about the NoResults refactor. Aside from that, looks _clean_!

2022-01-31 22:17 UTC, jmtaber129 commented
* Re: issue 1 - Changed to only show the search bar when there are more than 5 items, since this seems to be around when a scrollbox is necessary.
* Nice catch on issue 2 - This just needed to pass in the `keepParentFocus` flag to the `Menu` component to prevent the search box from keeping/stealing focus (if the search box was scrolled out of view, the search box would regain focus when any part of the menu is clicked, including when attempting to select an item).  Fixed.
* Refactored out the `NoResults` component into an `EmptyDropdownMenuItemLabel` component.

2022-02-04 16:45 UTC, mattkrick commented
Retested & works great! 👍

2022-02-04 16:45 UTC, merged