Fix type mismatch GraphQL
ParabolInc/parabol pull request #6151
Opened 2022-03-02 22:12 UTC by tianrunhe

Fixed #5644

2022-03-03 15:04 UTC, Dschoordsch requested changes

2022-03-03 15:04 UTC, Dschoordsch commented on packages/server/graphql/mutations/updateTeamName.ts
> +    args: {updatedTeam: UpdatedTeamInputType},
+1 we could still destructure here

2022-03-03 16:36 UTC, mattkrick commented
This is caused by a bug in GraphQL. 
It was fixed in v16 https://github.com/graphql/graphql-js/pull/3328
We're still pinned on v15 because our version of relay is old.
I recommend the following:
- Check to see if the latest version of relay supports graphql v16
- bump to the latest version of relay & latest version of graphql in a separate PR
- come back to this PR & amend it with the fixed typings

2022-03-04 00:48 UTC, tianrunhe commented
> This is caused by a bug in GraphQL. It was fixed in v16 [graphql/graphql-js#3328](https://github.com/graphql/graphql-js/pull/3328) We're still pinned on v15 because our version of relay is old. I recommend the following:
> 
> * Check to see if the latest version of relay supports graphql v16
> * bump to the latest version of relay & latest version of graphql in a separate PR
> * come back to this PR & amend it with the fixed typings

Looks like the latest relay v13.1.1 supports to [GraphQL v15.3.0](https://github.com/facebook/relay/blob/v13.1.1/package.json#L55)

2022-03-04 09:15 UTC, Dschoordsch approved these changes

2022-03-04 09:36 UTC, Dschoordsch commented
Did some smoke tests (creating team, creating reflection, updating team name and add task due date) and still works.

2022-03-04 21:12 UTC, mattkrick commented
ah such a bummer about relay!
Looks like it was working in their RC https://github.com/facebook/relay/issues/3705, but maybe it didn't land in the official release?

2022-03-16 22:23 UTC, mattkrick commented
LGTM

2022-03-16 22:24 UTC, merged