feat: Added button to export to pdf (#2730)
ParabolInc/parabol pull request #6420
Opened 2022-04-19 16:50 UTC by atannus

- Implements component for an "Export do PDF" button.
- Adds PDF button to SummarySheet.
- Hides buttons on PDF using "hide-print".

2022-04-20 13:37 UTC, Dschoordsch commented
@BartoszJarocki could you please review this?

2022-04-25 14:03 UTC, BartoszJarocki requested changes

2022-04-25 14:03 UTC, BartoszJarocki commented on packages/client/modules/email/components/SummaryEmail/ExportToPDF.tsx
> +}
-1 when working with inline styles, please use the proper type, for example, `const linkStyle: React.CSSProperties`

2022-04-25 14:03 UTC, BartoszJarocki commented on packages/client/modules/email/components/SummaryEmail/ExportToPDF.tsx
> +class ExportToPDF extends Component<Props> {
-1 could you please convert this to the function component? also, there's no need for this to have any props

2022-04-25 14:03 UTC, BartoszJarocki commented on packages/client/modules/email/components/SummaryEmail/ExportToPDF.tsx
> +export default withAtmosphere(withMutationProps(ExportToPDF))
-1 no need to use these hoc's

2022-05-18 08:45 UTC, Dschoordsch commented
@atannus are you still working on this? Did you want another review round? If so make sure to press the refresh button next to the reviewer who requested changes, otherwise they probably miss it.

2022-05-18 11:53 UTC, atannus commented
@Dschoordsch I spoke with @ackernaut a few days ago, I believe the whole PDF endeavor is stalled pending a priorities review by the team.

2022-05-18 19:26 UTC, ackernaut commented
Yeah, we don’t want to provide a confusing experience around what’s basically 1) open the print dialog and 2) save as a PDF instead of sending to a printer. We’re not sure we want to recreate this view as a PDF and have 2 views to maintain: 1) the table-based summary 2) a PDF view of it

2022-06-06 04:55 UTC, BartoszJarocki commented
@atannus do you mind if I close this PR as it's pretty outdated? once we're back at this issue we can revisit it.

2022-06-06 20:40 UTC, BartoszJarocki commented
will do, thank you!

2022-06-06 20:40 UTC, closed without merging