feat(gitlab): refresh gitlab tokens
ParabolInc/parabol pull request #6594
Opened 2022-05-19 18:35 UTC by nickoferrall

Fixes https://github.com/ParabolInc/parabol/issues/6592

### Testing

- Change `await redis.set(key, tokenTTL, 'EX', tokenTTL)` to `await redis.set(key, tokenTTL, 'EX', 5)` in addTeamMemberIntegrationAuth.ts and gitlabLoaders.ts. This will set the TTL for the Redis key to 5 seconds.
- Reintegrate with GitLab
- Open a Poker meeting and see that the meeting still works and you can see your GitLab issues
- Now, in gitlabLoaders, comment out the refresh token logic beginning on line 28 `if (!isValidAuth) {`
- Reintegrate with GitLab
- After 5 seconds, create a Poker meeting and now you won't be able to see any of your GitLab issues

2022-05-23 09:31 UTC, igorlesnenko requested changes
I would suggest to store TTL in a `teamMemberIntegrationAuths` where token lives.

I don't see that redis gives us functionality that couldn't be implemented in postgres in this particular case.

If we store it in a PostgreSQL, we don't need any additional query, as we can just fetch datetime and check that in code.

As alternative, we can just use try catch, if gitlab returns an error we refresh the token.

What do you think?

2022-05-23 16:13 UTC, nickoferrall commented on packages/server/dataloader/gitlabLoaders.ts
> +            const expiresAtTimestamp = new Date().getTime() + (expires_in - 30) * 1000
`expires_in is in seconds. Minus 30 to be safe. *1000 to convert it to milliseconds

2022-05-23 16:15 UTC, nickoferrall commented
I've pushed an update using the postgres table rather than Redis. Ready for your review @igorlesnenko. 

Fingers crossed it can be squeezed into the ship this week so we can launch GitLab on Wednesday 🤞

2022-05-24 19:39 UTC, Dschoordsch requested changes
Only small things, feel free to merge after fixing. Did not test.

2022-05-24 19:39 UTC, Dschoordsch commented on packages/server/dataloader/gitlabLoaders.ts
> +          return gitlabAuth as IGetTeamMemberIntegrationAuthQueryResult | null
-1 why add `| null` when we know it is `!== null` from l22?

2022-05-24 19:39 UTC, Dschoordsch commented on packages/server/integrations/helpers/authorizeOAuth2.ts
> +    expires_in: number | undefined
-1 we're fixing the other fields names to camelCase, so please do it also for `expiresIn`

2022-05-25 09:10 UTC, merged