feat(jira-server): Always show provider row with contact us button
ParabolInc/parabol pull request #6683
Opened 2022-06-07 10:34 UTC by igorlesnenko

Fixes #6269 and adds some markup fixes

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/466991/172358771-4eab81cb-247e-40ec-953c-419c0e1361b5.png">

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/466991/172359134-ab9bf056-3530-464f-a9ea-0b3eaca86394.png">

## Testing scenarios

- Create new org and team
- Go to integrations page
- See Jira server row is visible with `contact us` button
- Click `contact us`, see a new tab opened with a contact form with pre-filled subject

2022-06-14 12:45 UTC, Dschoordsch approved these changes
Looks good for me.
@lorena-cure what do you think releasing this row with contact link to the general public?

2022-06-14 14:07 UTC, lorena-cure commented
It looks good to me to. I think it's a good way of releasing it despite needing the setup on our end. 
Could I see though what the pre-filled form would look like? Just making sure it's clear for users that they are requesting the integration.

2022-06-14 14:42 UTC, igorlesnenko commented
@lorena-cure 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/466991/173605811-5e34f813-4e03-4ef5-92fc-b057ef075003.png">

2022-06-14 14:45 UTC, Dschoordsch commented
@tianrunhe from the analytics point of view, should we pass some utm parameters to the contact page for this?

2022-06-15 00:36 UTC, tianrunhe commented
> @tianrunhe from the analytics point of view, should we pass some utm parameters to the contact page for this?

I don't have particular tension on this but I'll let @lorena-cure or @avivapinchas decides.

2022-06-15 01:05 UTC, avivapinchas commented
> should we pass some utm parameters to the contact page for this?

Great Q! I believe we should *not*, and here's why: our GA instance runs across both the app and the website, so we can understand how folks are interacting with the totality of our offerings. I believe adding UTM parameters to the link will reset the session, so 2 bad things will happen: 
- We'll double-count that session
- We'll lose the data about where that user originally came from 

To understand whether folks engage with that button, we can do 2 other things: 
- Add a segment event, which we can see in Amplitude 
- In Google Analytics, we can see the previous page that someone viewed before coming to the Contact page 

cc @tghanken to confirm that I actually understand GA though 🙃 

For future ref, UTM parameter standards are [logged in Notion here](https://www.notion.so/parabol/UTM-Parameters-Guidelines-f2e1ada7e80042ff90a304d6511d9e27) 🔒 . 

And one Q while I'm here: is this going to the Contact Us page? I believe it should go to a dedicated Jira Server integration landing page, that has a specific form for this request at the bottom - cc @lorena-cure The reasons for that: we can better gauge interest by looking at traffic to that page, we could customize the form to send some metadata about the request, to make it easier to see that it's a Jira Server request for team members responding to it, and we can gauge interest by looking at form submissions.

2022-06-15 09:22 UTC, Dschoordsch requested changes

2022-06-15 09:22 UTC, Dschoordsch commented on packages/client/modules/teamDashboard/components/ProviderRow/JiraServerProviderRow.tsx
> +                    viewerId: id
-1 I missed this before, but this is the team member id, not the viewer user id.

2022-06-15 09:29 UTC, lorena-cure commented
+1 to Aviva's comment. 
I also think it should go to a dedicated Jira Server contact us page, if we have a customized copy and form, it will create less friction. 

I can create this page and form @igorlesnenko

2022-06-15 11:20 UTC, igorlesnenko commented
@lorena-cure it would be great, waiting for the new page url, and I'll update my PR

2022-06-15 15:10 UTC, tghanken commented
> > should we pass some utm parameters to the contact page for this?
> 
> Great Q! I believe we should _not_, and here's why: our GA instance runs across both the app and the website, so we can understand how folks are interacting with the totality of our offerings. I believe adding UTM parameters to the link will reset the session, so 2 bad things will happen:
> ...

This is correct!  GA picks the latest set of used UTM parameters when calculating attribution, so we should rely on Segment for any additional analytics here.

2022-06-21 06:40 UTC, Dschoordsch approved these changes

2022-06-21 20:02 UTC, merged