feat: cards should be full width on mobile, width should be more flui…
ParabolInc/parabol pull request #6684
Opened 2022-06-07 15:19 UTC by BartoszJarocki

…d and the whole grid centered

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-06-08 13:22 UTC, BartoszJarocki commented on packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
> +    width: `calc(100% / 5 - ${ResponseCardDimensions.GAP}px)`
as the `grid` we're using is really just a flexbox that wraps into multiple rows there's no better way of splitting it into responsive columns

2022-06-08 13:25 UTC, BartoszJarocki commented
@jmtaber129 would you mind taking a look?

2022-06-08 18:10 UTC, jmtaber129 requested changes
Looks way better!  Just one thing about how we're calculating breakpoint widths

2022-06-09 06:11 UTC, BartoszJarocki commented on packages/client/components/TeamPrompt/TeamPromptGridDimensions.ts
> +    ResponseCardDimensions.PREFERRED_RESPONSE_WIDTH * 2 + ResponseCardDimensions.GAP,
very true! things got a bit too cryptic. I've changed the calculations and added some comments

2022-06-09 06:11 UTC, BartoszJarocki commented on packages/client/components/TeamPrompt/TeamPromptGridDimensions.ts
> +  PREFERRED_RESPONSE_WIDTH: 360
that's a better name, fixed

2022-06-09 06:12 UTC, BartoszJarocki commented
@jmtaber129 would you mind doing another round? thanks!

2022-06-09 16:08 UTC, merged