Jmtaber129/standups links
ParabolInc/parabol pull request #6701
Opened 2022-06-08 21:06 UTC by jmtaber129

# Description

Fixes https://github.com/ParabolInc/parabol/issues/6630
Support for:
- [X] Pasting links
- [X] Previewing link on selection
- [X] Editing links via existing menu
  - [X] Edit href of link via existing menu
  - [ ] Edit text of link via existing menu (TODO)
- [X] Removing links
- [ ] Clicking link while editing without opening link + opening link on click when not editing (TODO)

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-06-15 13:15 UTC, BartoszJarocki commented
@jmtaber129 before I dig into the code, I have a couple of UI questions

1. the link editor popover opens far from the link and looks a bit confusing, can we make it appear closer, preferably just below the edit link? 
<img width="894" alt="Screenshot 2022-06-15 at 15 07 57" src="https://user-images.githubusercontent.com/1017620/173835495-21d753b4-f920-4967-be51-7366f4df9e4f.png">

The same goes for link preview
<img width="723" alt="Screenshot 2022-06-15 at 15 07 50" src="https://user-images.githubusercontent.com/1017620/173835668-bd3a065c-b65d-4471-9fa3-5e3ae1944946.png">


2. a little nit, can we make padding the same on each side (top,bottom, left, right)  in the link editor? 
<img width="894" alt="Screenshot 2022-06-15 at 15 07 57" src="https://user-images.githubusercontent.com/1017620/173835722-dbaaa61d-0ec1-4c14-8f45-d32602d0af9a.png">

visually bottom padding is bigger and I think it'd be nice to improve that

2022-06-22 06:12 UTC, BartoszJarocki approved these changes
great work!

2022-06-22 06:12 UTC, BartoszJarocki commented on packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx
> +  const handleSubmit = ({text, href}) => {
+1 types please, no implicit any

2022-06-22 16:47 UTC, mattkrick requested changes

2022-06-22 16:47 UTC, mattkrick commented on packages/client/components/EditorLinkViewer/EditorLinkViewerTipTap.tsx
> +      tiptapEditor.commands.setTextSelection({to: to - 1, from: from - 1})
note to self: test with emojis or any other 2 char unicode

2022-06-22 16:47 UTC, mattkrick commented on packages/client/components/EditorLinkChanger/EditorLinkChangerTipTap.tsx
> +    <EditorLinkChangerModal
+2 whoa! i'm impressed you could use this for both tiptap & draft

2022-06-22 16:47 UTC, mattkrick commented on packages/client/components/promptResponse/PromptResponseEditor.tsx
> +    {text: string; href: string; originCoords: BBox} | undefined
+1 nit: since LinkMenu & LinkPreview are mutually exclusive, you could express that relation by reusing the same state.

2022-06-22 16:47 UTC, mattkrick commented on packages/client/components/promptResponse/tiptapConfig.ts
> +  setLinkMenuProps?,
-1 noImplicitAny

2022-06-22 16:47 UTC, mattkrick commented on packages/client/components/promptResponse/tiptapConfig.ts
> +  Link.extend({
really cool how tiptap does this!

2022-06-23 23:25 UTC, mattkrick commented
Looking GREAT! Just a couple usability things:

- [ ] when the caret is at the end of a link & i hit the space bar, the space should _not_ be a part of the link (similar to how google docs works)
- [ ] before the linkpreview or link changer modal is open, the entire link should be highlighted (same as GDocs)
- [ ] with the linkpreview or link editor modal open, when I hit ESC tiptap should regain focus & the selection should be the whole link

2022-06-24 17:00 UTC, jmtaber129 commented
@mattkrick I fixed the last bullet, but not the first two - I agree that those should be fixed, but because the fixes may be a bit more involved, and they're also consistent with the existing link behavior in the Draft editor, I'd prefer to get this landed as-is.

2022-06-24 20:18 UTC, jmtaber129 commented
Weird, for some reason I could've sworn draft was doing the same thing for me.  I went ahead and fixed (1), and I'll create a follow-up issue to address (2)

2022-06-24 20:52 UTC, merged

2022-06-24 20:54 UTC, jmtaber129 commented
Opened https://github.com/ParabolInc/parabol/issues/6832 to track showing the highlighted text while the link changer is open