feat: Improve clarity of Integrations page
ParabolInc/parabol pull request #6804
Opened 2022-06-22 11:01 UTC by igorlesnenko

Fixes #5875
Fixes #6797

<img width="791" alt="image" src="https://user-images.githubusercontent.com/466991/175012964-48e44e64-f0cc-4ca2-bc0f-6bd3a6192bff.png">

**How to test:**

- Make all integrations visible (Add feature flags for Azure DevOps and MS Teams, add Azure DevOps provider)
- Check that all integrations can be connected and all controls are working as expected
- Check mobile markup

2022-06-22 17:29 UTC, enriquesanchez approved these changes
I can't speak for everything else, but the new placeholder text for the webhooks looks good to me 👍

2022-06-22 17:35 UTC, enriquesanchez commented
Two additional notes, but **these can be handled on separate PRs**:

1. Can we increase the spacing around the description text and the Connected and Available sub-headings? You can reference the mockup on https://github.com/ParabolInc/parabol/issues/5875.

2. Where you able to [look at this comment](https://github.com/ParabolInc/parabol/issues/5875#issuecomment-1133093531) from that same issue?

>Add a See how it works link to the description of each integration that links to a support/help document that highlights how to use it.

2022-06-23 09:22 UTC, igorlesnenko commented
> Where you able to https://github.com/ParabolInc/parabol/issues/5875#issuecomment-1133093531 from that same issue?
@enriquesanchez yeah, I added the link. Does it look correct?

<img width="783" alt="image" src="https://user-images.githubusercontent.com/466991/175265025-e813b353-6c54-4de8-a118-343346bb4ddf.png">

2022-06-23 10:23 UTC, nickoferrall approved these changes
This looks great - I really like separating the Connected vs Available providers!

2022-06-23 10:23 UTC, nickoferrall commented on packages/client/modules/teamDashboard/components/ProviderRow/ProviderRow.tsx
> +      {children}
+2 great work making this reusable so we can save a ton of CSS in the other components!

2022-06-23 10:23 UTC, nickoferrall commented on packages/client/modules/teamDashboard/components/ProviderRow/ProviderRow.tsx
> +            <a href={seeHowItWorksUrl} target='_blank' rel='noreferrer'>
+1 I'd make this text a bit bolder. I actually didn't notice it was a hyperlink until I looked on mobile

2022-06-23 11:42 UTC, igorlesnenko commented
@enriquesanchez @nickoferrall Updated the layout:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/466991/175290764-1eb8178c-99bb-4993-a75c-69153b53e246.png">

2022-06-24 09:22 UTC, igorlesnenko commented
See how it works URLs will be updated with correct support pages

2022-07-04 16:50 UTC, Dschoordsch requested changes

2022-07-08 16:44 UTC, Dschoordsch approved these changes
Did not test again, but code looks good!

2022-07-08 16:44 UTC, Dschoordsch commented on packages/client/modules/teamDashboard/components/ProviderRow/StyledButton.tsx
> +const StyledButton = styled(FlatButton)({
+1 Could get a better name, like in what way is it styled differently than `FlatButton`?

2022-07-13 17:26 UTC, merged