fix: Contrast of selected highlight of the current phase is low
ParabolInc/parabol pull request #6940
Opened 2022-07-26 12:33 UTC by raj360

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]
Fixed the difference in contrast of the current phase

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Ensure the Home navigational style and the selected phase are the same 

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

2022-07-29 07:16 UTC, Dschoordsch commented
@raj360 thanks for working on this, can you please link the original issue so we know what the description was?

2022-08-04 07:52 UTC, gitstart commented
@Dschoordsch the original issue is already linked in the PR description. @igorlesnenko please can you also help review this

2022-08-08 11:27 UTC, igorlesnenko requested changes
Thank you for the PR!

I found few issues while I was testing it:

- There is now a gap between list items
- When I switch from one item to another it shifts from its position a little bit.
- Sub items still have previous bg color (for example icebreaker or discussion items)

Here is the demo:

https://user-images.githubusercontent.com/466991/183406915-131c166e-17be-4f57-b6e1-d4bb80bca019.mov

@enriquesanchez can you confirm that the color is correct?

2022-08-10 05:21 UTC, raj360 commented
Hey @igorlesnenko, you mind checking in once again, your reviews have been attended to.

2022-08-10 12:16 UTC, igorlesnenko approved these changes
Thank you! It now looks good! Lets wait for @enriquesanchez review too

2022-08-15 15:52 UTC, enriquesanchez requested changes
Thanks for the great work @raj360, and thank you for the ping @igorlesnenko 👍 

Because the background of the meeting sidebar is white, `SLATE 300` feels much more darker here. It think we can use `SLATE 200` instead, and that should feel more balanced.

2022-08-16 13:26 UTC, raj360 commented
Hey @enriquesanchez , requested changes have been  implemented please take another look.

2022-08-16 21:18 UTC, enriquesanchez commented
Thanks @raj360! I'm having trouble testing your branch on my local environment. Would you mind sharing a screen capture of the updates so I can see the new highlight color?

2022-08-17 11:34 UTC, Dschoordsch requested changes
Looks good, only 1 question.

2022-08-17 11:34 UTC, Dschoordsch commented on packages/client/components/MeetingSubnavItem.tsx
> +    '&:hover, :focus': {
-1 Is there a reason you've added `focus` here? It appears to me as if this could conflict with `isActive`.

2022-08-19 11:36 UTC, gitstart-instrumental commented
> # Description
> Fixes/Partially Fixes #6176 [Please include a summary of the changes and the related issue] Fixed the difference in contrast of the current phase
> 
> ## Demo
> [If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]
> 
> ## Testing scenarios
> [Please list all the testing scenarios a reviewer has to check before approving the PR]
> 
> * [ ]  Scenario A
>   
>   * Ensure the Home navigational style and the selected phase are the same
> 
> ## Final checklist
> * [x]  I checked the [code review guidelines](../docs/codeReview.md)
> * [x]  I have performed a self-review of my code, the same way I'd do it for any other team member
> * [x]  I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
> * [x]  Whenever I took a non-obvious choice I added a comment explaining why I did it this way
> * [x]  I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
> * [x]  PR title is human readable and could be used in changelog



> Thanks @raj360! I'm having trouble testing your branch on my local environment. Would you mind sharing a screen capture of the updates so I can see the new highlight color?

![chrome_bN1G6fKzsl](https://user-images.githubusercontent.com/31279142/185589107-571e799f-dfdb-4a8f-8bff-b988f31a1e32.png)
![chrome_eFJTvTHn5N](https://user-images.githubusercontent.com/31279142/185589208-ef2642e8-d877-4cf0-9c64-a40feeb11de0.png)

2022-08-19 15:27 UTC, enriquesanchez approved these changes
From a design stand point, the new highlight color looks good to me 👍 

Thank you @raj360!

2022-08-22 18:53 UTC, Dschoordsch approved these changes

2022-08-22 18:53 UTC, merged