feat: Updated new meeting settings area
ParabolInc/parabol pull request #6989
Opened 2022-08-02 18:04 UTC by igorlesnenko

Fixes #5603

<img width="919" alt="image" src="https://user-images.githubusercontent.com/466991/182443290-6f99b637-9fbd-4622-aa3e-fcea920ad8ad.png">

<img width="361" alt="image" src="https://user-images.githubusercontent.com/466991/182443361-8553af5e-bcfb-4bfb-b651-24f256a3256e.png">

2022-08-08 11:08 UTC, igorlesnenko commented
@JimmyLv can you review this PR please?

2022-08-08 14:45 UTC, JimmyLv approved these changes
LGTM! Great to see we have a prettier new meeting settings area 👍

2022-08-08 14:45 UTC, JimmyLv commented on packages/client/components/NewMeeting.tsx
> +  [MEDIA_QUERY_FUZZY_TABLET]: {
+2 #TIL I like the pattern of handling responsive styles this way, rather than by `isDesktop`

2022-08-09 22:52 UTC, mattkrick commented
+1 For mobile, can we center the active meeting in the carousel so the previous & next options are both slightly visible? that way folks can go back & forth just by tapping instead of swiping

2022-08-09 22:54 UTC, mattkrick requested changes
see comment on centering active meeting

2022-08-10 20:16 UTC, igorlesnenko commented
@mattkrick I tried to fix that quickly, but was unable to, as possibly, there is a bug in the library.

Also, since in this PR I only touched settings part of the dialog, I created a separate issue and will look into it: #7040

Is it ok?

2022-08-12 01:50 UTC, mattkrick commented
@igorlesnenko i think i got it working: https://www.loom.com/share/d9a85b1904be463ea3cb7401e8f4e47d

If you like what you see, go ahead & merge https://github.com/ParabolInc/parabol/pull/7061 into this PR.

aside from that, lgtm

2022-08-12 13:44 UTC, igorlesnenko commented
@mattkrick I left comments in your PR: https://github.com/ParabolInc/parabol/pull/7061#pullrequestreview-1071109618

I'm merging this PR for now

2022-08-12 13:44 UTC, merged