Fix: carousel
ParabolInc/parabol pull request #7061
Opened 2022-08-12 01:49 UTC by mattkrick

Fixes carousel sliding: https://www.loom.com/share/d9a85b1904be463ea3cb7401e8f4e47d

2022-08-12 01:52 UTC, mattkrick commented on packages/client/components/NewMeetingCarousel.tsx
> +        slidesPerView={1.99}
there's some magic here. if we `2` slides are visible, then it won't `slideToClickedSlide` for the 2nd slide moving forward or slide 1 when moving backwards :shrug:

2022-08-12 13:41 UTC, igorlesnenko requested changes
I see a couple of issues now

1) The card on mobile is not centered correctly

<img width="417" alt="image" src="https://user-images.githubusercontent.com/466991/184365516-1846ce2c-b609-420a-a78e-da9d724593cc.png">

This is because library does not consider `slidesOffsetBefore={24}` when calculating center. (Feels like bug in the library)

2) Card on mobile became smaller now, and the description is trimmed

3) Now we show 3 cards instead of 4 on desktop, and the latest one is cut just a little bit

<img width="875" alt="image" src="https://user-images.githubusercontent.com/466991/184363358-1c5ad293-33ff-4999-804b-3cdba8a1b122.png">

This may give the feeling that we have only three types of meetings.

Comparing to previous setup:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/466991/184363552-53ac63ba-fe0c-426d-a3b1-d9c1d5b7bda6.png">

Is showing 3 cards better?

2022-08-12 23:24 UTC, mattkrick commented
all good points!
we could set a min width for card sizes (216px looks like the best bet to keep the subtitles from condensing) 
the off center thing is infuriating, at least it's a _little_ more centered than before? :sweat_smile: 
i get why it works the way it does, but i'm not sure how to get around it. maybe we add in an empty slide on the front & back & disallow folks from navigating to them? that'll add padding and keep things centered.

up to you if you wanna keep the changes or merge without! i think what you've got is good enough to move forward with

2022-08-17 18:09 UTC, igorlesnenko commented
@mattkrick what if we do without `centeredSlidesBounds` option. I pushed a new PR: #7079
What do you think?

2022-08-25 16:12 UTC, closed without merging