fix: hyperlink default focus
ParabolInc/parabol pull request #7078
Opened 2022-08-17 16:28 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/6975

https://www.loom.com/share/3cb5f3c909474f95be24fa92ab299281

### To test

- [ ] In standups, if the user selects some text and presses cmd + k, the hyperlink modal focuses on the link input rather than the text input
- [ ] When using the hyperlink modal in any meeting type, if the text the user highlights is trimmed
- [ ] If the user highlights empty text, the focus remains on the text input

2022-08-17 16:29 UTC, nickoferrall commented on packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
> -              autoFocus={link === null && text !== ''}
`link` could be an empty string which is why there wasn't any autofocus

2022-08-18 05:30 UTC, jmtaber129 requested changes
Thanks for looking into this! It's hard to think of a case when someone would intentionally create a link with a preceding space.

-1 There is one edge case that I think needs to be addressed - if I select text with spaces that would be trimmed and then add a link, those spaces are deleted after I hit submit.  E.g. if I have text `"cool thing"`, highlight the text `" thing"` (with space), add a link, and submit, the text becomes `"coolthing"`.

This probably means doing the trimming in the Draftjs-/TipTap-specific link changer modals by changing the selection to exclude spaces before grabbing the link text.

2022-08-18 09:48 UTC, nickoferrall commented
Good find! That looks like a separate issue that's happening in prod, so I've created an issue for that: https://github.com/ParabolInc/parabol/issues/7088

2022-08-19 19:13 UTC, jmtaber129 commented
Oof, you're right!

2022-08-23 09:44 UTC, merged