chore: add flowwer-dev/pull-request-stats github workflow
ParabolInc/parabol pull request #7111
Opened 2022-08-25 09:15 UTC by JimmyLv

# Description

![Google Chrome-LinearB Engineering Operational Excellence-000005-20220825](https://user-images.githubusercontent.com/4997466/186625264-6e4a6378-166b-4c88-9e42-33d0272a0ae2.png)

This PR adds usage of https://github.com/flowwer-dev/pull-request-stats workflow, use this Github action to print relevant stats about Pull Request reviewers.

The objective of this action is to:

- Reduce the time taken to review the pull requests.
- Encourage quality on reviews.
- Help deciding which people to assign as reviewers.

Please feel free to comment, let's just see how it works in this PR, please let me know what you think!

## Demo

![image](https://user-images.githubusercontent.com/4997466/186625234-982203de-bc5e-43b8-bf00-eed9dc361d21.png)

2022-08-25 11:14 UTC, Dschoordsch requested changes
Statistic looks nice, but I don't want to see this on every PR. Can we have this on a separate site?

2022-08-25 12:27 UTC, JimmyLv commented
> Statistic looks nice, but I don't want to see this on every PR.

Thanks for such quick feedback! It's a good point and one that's worth discussing.

I think the goal of this statistic is to ultimately shorten Cycle Time, to encourage Reviewers to do it faster, and to encourage the quality of reviews; Reviewers are also PR creators, so they can objectively see the process of each Reviewer (including themselves) when submitting a PR.

So it's a matter of "timing", and if it's put on a separate page, my concern is that people won't have as much of a chance to look at it, and thus the motivation will be less effective?

However, in the meantime, the other thing I'm considering: Will this put **_pressure_** on our process of doing a Review? 
I'm not sure, it might be worth trying, let me post to the `#engineering` channel to hear what others think ☺️

2022-08-25 14:22 UTC, JimmyLv commented
Thanks @BartoszJarocki for the feedback, yeah, I agree and support the idea that PR Review can't be a competition. 
Seeing the stats weekly or monthly, need to find a place to generate it, but if not do Pull Request inside, then I can't figure out where. 🤣 

I feel like we can make it optional, through PR's Label, like when manually adding `"pr_stats"` label, this GitHub Action Bot 🤖 will add a comment.
 From there it can become more flexible, and following this pattern, we can also add more bots to PR later.

2022-08-25 14:40 UTC, Dschoordsch commented
I would like to see those stats in Slack once a week in fridayship or at the end of every sprint before the retro. Having these every Friday is probably easier.

2022-08-25 15:17 UTC, nickoferrall commented
Feels safe to try! If the aim is to increase cycle time, perhaps we should sort by "Time to review" rather than "Total comments"?

2022-08-25 15:21 UTC, JimmyLv commented
@nickoferrall Yeah, I've updated before for ["TIME"](https://github.com/flowwer-dev/pull-request-stats#action-inputs) as a sorting option. But it seems that the Bot recognizes the existing stats comment and stops regenerating again, so let me delete the comment and try running workflow again. 😂

2022-08-31 12:42 UTC, JimmyLv commented
@Dschoordsch After reconfirming, the [Slack integration](https://github.com/flowwer-dev/pull-request-stats#slack-integration) requires monthly sponsorship (min $20 usd / month) [^1], so it's not available to integrate with Slack to send weekly reports for now. 🤣

> we can make it optional, through PR's Label, like when manually adding the "pr_stats" label, this GitHub Action Bot 🤖 will add a comment.

So, I'd still recommend making this workflow optional, and I've changed the relevant configuration in the `yml` file. So that we can look at it manually when we want to, and then I'll make it automated later if necessary. 😁

[^1]: https://github.com/flowwer-dev/pull-request-stats#premium-features-

2022-09-02 08:09 UTC, Dschoordsch commented
Let's try it with Slack.

2022-09-02 08:09 UTC, merged