feat(metrics): Add Task Estimate Set event
ParabolInc/parabol pull request #7117
Opened 2022-08-26 00:05 UTC by tianrunhe

# Description

Fixes #7116, based on #7067 
## Demo

<img width="388" alt="Screen Shot 2022-08-25 at 5 02 54 PM" src="https://user-images.githubusercontent.com/1879975/186789521-fdafe4bd-f9cd-4dba-8151-6569aa02fa8d.png">

<img width="431" alt="Screen Shot 2022-08-25 at 5 03 12 PM" src="https://user-images.githubusercontent.com/1879975/186789549-1ce4c12b-9ba6-4e30-8baf-1819b97e797e.png">

## Testing scenarios

- [ ] Success task estimate push
  - In the estimate phase of a poker meeting, try to push a score to Jira, with valid dimension setting
  - Verify the properties in Segment

- [ ] Failed task estimate push
  - In the estimate phase of a poker meeting, try to push a score to Jira, with invalid dimension setting (e.g., issues within Jira screens)
  - Verify the properties in Segment

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

2022-08-29 10:27 UTC, Dschoordsch requested changes

2022-08-29 10:27 UTC, Dschoordsch commented on packages/client/mutations/SetTaskEstimateMutation.ts
> +      SendClientSegmentEventMutation(atmosphere, 'Task Estimate Set', {
+1 Can we move this to the server side to simplify this?

2022-08-29 22:19 UTC, tianrunhe commented
@Dschoordsch I didn't implement it on the server side as I found it a bit tedious... I took a closer look and came up with this slightly better version. Let me know what you think!

2022-08-30 10:08 UTC, Dschoordsch approved these changes
The resolver got even messier than before :-/
We should clean this one up at some point.

2022-08-30 15:21 UTC, merged