Fix/6946 bug demo starts on refresh
ParabolInc/parabol pull request #7131
Opened 2022-08-30 12:04 UTC by JimmyLv

# Description

Fixes/Partially Fixes #6946 
prevent demo meeting auto-start after page refresh

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-09-01 16:05 UTC, Dschoordsch requested changes

2022-09-02 08:53 UTC, JimmyLv commented on packages/client/modules/demo/ClientGraphQLServer.ts
>      // const isStale = false
sure

2022-09-02 08:58 UTC, JimmyLv commented on packages/client/modules/demo/ClientGraphQLServer.ts
> +    const isUpdatedIn5Minutes =
I updated the name to `isFresh`, should also state the intent 😁 let me know if `isStale` is better.

2022-09-02 11:36 UTC, Dschoordsch approved these changes

2022-09-13 00:09 UTC, mattkrick commented
LGTM!

2022-09-13 00:09 UTC, merged