Fix/6062/use svg icons
ParabolInc/parabol pull request #7154
Opened 2022-09-06 09:55 UTC by Dschoordsch

# Description

Fixes #6062

Replace 
## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-09-19 10:35 UTC, Dschoordsch commented
The current implementation increases the bundle size. Since the images are components, these are also not cached, degrading the performance overall.

2022-09-24 15:40 UTC, 87prashant commented
> degrading the performance overall

That's sad, any way we can improve it?

2022-09-26 07:56 UTC, Dschoordsch commented
> > degrading the performance overall
> 
> That's sad, any way we can improve it?

I think we have to go the SVG route, i.e. downloading the used icons as SVG and using those as images. This will probably not change the download size much, but it makes it possible to cache the images in the browser. As components these will need to be loaded each release. Not a huge deal, but when we touch this, we should do it right.

2022-10-20 11:32 UTC, Dschoordsch commented
> > > degrading the performance overall
> > 
> > 
> > That's sad, any way we can improve it?
> 
> I think we have to go the SVG route, i.e. downloading the used icons as SVG and using those as images. This will probably not change the download size much, but it makes it possible to cache the images in the browser. As components these will need to be loaded each release. Not a huge deal, but when we touch this, we should do it right.

I made a mistake when measuring as I did not properly minimize the chunks (I did not pass `--deploy`). When properly done, the size is virtually identical, so we can move on with this.

2022-10-20 14:30 UTC, Dschoordsch commented
@igorlesnenko I know you've taken a look at this before the rebase, but could you please just do a quick glance over if there is something obviously wrong?

2022-10-20 14:49 UTC, 87prashant requested changes

2022-10-24 17:40 UTC, igorlesnenko requested changes
What has caught my eye:

Checkbox is now too close:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/466991/197582595-c6aa4758-b901-4744-9eaf-a1a75cfd8fc1.png">

Different checkbox sizes:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/466991/197590026-ad4c7b4a-182d-471e-bd31-767db1f9a519.png">

Next button is a half-pixel bolder than it was. Maybe not critical.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/466991/197582831-8840624d-46f9-4551-949c-c61f5aab21ed.png">

Everything else looks good

2022-11-02 13:29 UTC, Dschoordsch commented on packages/client/components/BottomControlBarReady.tsx
> +      // without fill property the icon will have different color inside
updated it

2022-11-02 14:46 UTC, igorlesnenko approved these changes
LGTM!

2022-11-03 15:43 UTC, merged