Add metrics about `disableAnonymity` in retro meetings
ParabolInc/parabol pull request #7171
Opened 2022-09-12 22:46 UTC by tianrunhe

# Description

Fixes #7163 

## Demo
New property `disableAnonymity` included in Meeting related events:
<img width="479" alt="Screen Shot 2022-09-12 at 3 43 30 PM" src="https://user-images.githubusercontent.com/1879975/189771142-5d25608c-adb1-4872-919c-fbdd806e78f6.png">

New event `Meeting Settings Changed` published to Segment:
<img width="464" alt="Screen Shot 2022-09-12 at 3 42 39 PM" src="https://user-images.githubusercontent.com/1879975/189771042-38b78dfe-96dd-40ee-91c6-dcd4545523aa.png">

## Testing scenarios

- [ ] New property `disableAnonymity` included in Meeting related events
  - Start/Join/Complete a meeting
  - Verify `disableAnonymity` is included in the relevant events in Segment

- [ ] New event `Meeting Settings Changed` published to Segment:
  - Go to meeting selector modal
  - Toggle the `Anonymous reflections` setting
  - Verify a new `Meeting Settings Changed` event was published and the `disableAnonymity` property is expected

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

2022-09-13 14:13 UTC, igorlesnenko requested changes
- Open retro settings 
- remove checkbox from anonymous reflections, see in segment logs:
```
disableAnonymity: true,
    hasIcebreaker: false,
```

I guess `hasIcebreaker` should be true?

2022-09-14 09:06 UTC, igorlesnenko approved these changes

2022-09-14 14:12 UTC, Dschoordsch requested changes

2022-09-14 14:12 UTC, Dschoordsch commented on packages/server/graphql/mutations/setMeetingSettings.ts
> +    const meetingSettings = {}
-1 You can type this here `const meetingSettings = {} as MeetingSettings` then you don't need to do the `Object.assign` trick to bypass typings.

2022-09-14 14:12 UTC, Dschoordsch commented on packages/server/graphql/mutations/setMeetingSettings.ts
> +          Object.assign(meetingSettings, {hasIcebreaker: checkinEnabled})
-1 If you type it properly, you can just do `meetingSettings.hasIcebreaker = checkinEnabled` here which is more readable.

2022-09-14 14:12 UTC, Dschoordsch commented on packages/server/graphql/mutations/setMeetingSettings.ts
> +          Object.assign(meetingSettings, {disableAnonymity})
-1 `meetingSettings.disableAnonymity = disableAnonymity`

2022-09-15 10:19 UTC, Dschoordsch approved these changes

2022-09-15 17:19 UTC, merged