fix(Jira): show only available fields in Sprint Poker
ParabolInc/parabol pull request #7257
Opened 2022-10-10 08:59 UTC by Dschoordsch

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-10-12 10:29 UTC, nickoferrall commented
Hey @Dschoordsch, are there any testing steps that you'd like us to follow?

2022-10-12 15:49 UTC, nickoferrall approved these changes
Great work! This passed all the testing steps and the code LGTM. I imagine this was a painful one to work on - I'm excited that there's light at the end of the Jira bug tunnel 🙌

2022-10-12 15:49 UTC, nickoferrall commented on packages/server/dataloader/atlassianLoaders.ts
> +            Object.entries<any>(issueRes.editmeta?.fields)?.forEach(([fieldId, {schema}]) => {
+1 could add a type that includes `schema` here

2022-10-12 15:49 UTC, nickoferrall commented on packages/server/graphql/mutations/setTaskEstimate.ts
> +            dimensionField.issueType = issueType
+2 nice way of handling anything Jira throws at us

2022-10-12 15:49 UTC, nickoferrall commented on packages/server/graphql/public/mutations/updateJiraDimensionField.ts
> +    existingDimensionField?.fieldName === fieldName &&
+1 conditional can be removed here

2022-10-12 15:49 UTC, nickoferrall commented on packages/server/postgres/queries/getJiraDimensionFieldMap.ts
> +  return res as JiraDimensionFieldMap[]
Why do we need the casting here and `as any` on the line above?

2022-10-12 15:49 UTC, nickoferrall commented on packages/client/components/JiraFieldMenu.tsx
> -  const {cloudId, projectKey, possibleEstimationFieldNames} = integration
+1 this isn't the line of code where the problem is happening, but I wanted to note it down:

If a project doesn't have a Story Points field, the menu should probably not show the divider or the padding at the top:
![jira-menu](https://user-images.githubusercontent.com/39854876/195387433-991884ed-7e7e-4811-8c08-aac3fe594264.png)

2022-10-12 16:03 UTC, Dschoordsch commented
@tianrunhe you were added as a reviewer automatically because I added a migration. Do you think we should add any analytics to any of the logic?

2022-10-12 16:45 UTC, tianrunhe requested changes
Thanks for tagging me! Or thanks the robot for tagging me 🤣

While we are here, can we take the chance to add the missing metrics for the mutation `updatePokerScope`? Thank you!

- Event name: `Poker Meeting Scope Updated`
- Properties:
  - `meetingId`
  - `service`: the `TaskServiceEnum`
  - `taskId`
  - `action`: `ADD` or `DELETE`

2022-10-12 18:12 UTC, Dschoordsch commented
@igorlesnenko could you please also take a look? Because this is a bigger change, I would feel more comfortable if 2 people would review it.

2022-10-13 11:04 UTC, igorlesnenko approved these changes

2022-10-13 14:53 UTC, Dschoordsch commented
@tianrunhe We already have some tracking for this
https://github.com/ParabolInc/parabol/blob/49df2b9aaea8f645ccd81ec3b3202c2c286a8dae/packages/client/mutations/UpdatePokerScopeMutation.ts#L300
It was added on the client side, because only there we know whether or not the user used "select all"

2022-10-13 18:06 UTC, tianrunhe approved these changes
Sign off from metrics side

2022-10-14 15:56 UTC, igorlesnenko requested changes
Posting the issue in the correct PR:
Getting an error while running migration
```
> Migrating files:
> - 1663850062796_JiraDimensionFieldMap
> Rolling back attempted migration ...
error: duplicate key value violates unique constraint "JiraDimensionFieldMap_pkey"
```

2022-10-14 17:35 UTC, igorlesnenko approved these changes
The new migration works

2022-10-18 11:17 UTC, merged