fix: delete billing leader
ParabolInc/parabol pull request #7267
Opened 2022-10-11 16:57 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/6144

https://www.loom.com/share/81c633b5d1304c6fb8e8a76ee07c916a

2022-10-11 20:42 UTC, tianrunhe requested changes
The server side test [`Delete user`](https://app.circleci.com/pipelines/github/ParabolInc/parabol/7123/workflows/8f33e8e1-f858-40cc-a1e7-140838a7ed30/jobs/15927/tests) seems to fail consistently. Maybe you need to update the test code?

2022-10-12 10:21 UTC, nickoferrall commented
Thanks, @tianrunhe. The rethinkdb query had an additional bug - if there were no other users in the team, it would return an error. This wasn't getting picked up by the test as the rethink query would only be run for non-free users, and the test user is on the free tier. Update pushed!

2022-10-12 16:27 UTC, tianrunhe approved these changes

2022-10-13 08:12 UTC, Dschoordsch approved these changes
Tested, works.

2022-10-13 08:36 UTC, merged