fix: Filtering is still able to be done when only one state is available
ParabolInc/parabol pull request #7295
Opened 2022-10-14 07:52 UTC by gitstart

# Description
Filtering does not show if there is only one team member.
Filtering only shows if there is two or more team members.
Fixes/Partially Fixes #7018

# Loom video
https://www.loom.com/share/33e002ee39584a0fb70b02410fea8a84

## Testing scenarios

- [ ] Scenario A
  - Step 1
  - Start with one team member
  - Step 2
  - Start with two or more team members

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2022-10-14 07:54 UTC, gitstart commented
Hi @Dschoordsch, @igorlesnenko your reviews are required for this PR

2022-10-19 10:28 UTC, Dschoordsch commented
@JimmyLv can you please review?

2022-10-19 10:30 UTC, Dschoordsch commented
Realized you were on a couple of other review requests already.
@igorlesnenko could you please review?

2022-10-20 13:16 UTC, igorlesnenko requested changes
Still able to see the filter

![image](https://user-images.githubusercontent.com/466991/196959020-ad407c8b-47a4-47e4-aab2-e21c2e3f0685.png)

2022-10-20 13:16 UTC, igorlesnenko commented on packages/client/modules/teamDashboard/components/TeamTasksHeader/TeamTasksHeader.tsx
> +          {teamMembers.length && (
The condition should probably be `teamMembers.length` > 1 as I still able to see the filter with one member in the team

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/466991/196958914-0f99150e-b3b6-4be2-affd-949c787f6167.png">

2022-10-25 08:42 UTC, igorlesnenko approved these changes

2022-10-25 11:16 UTC, Dschoordsch approved these changes

2022-10-25 11:17 UTC, Dschoordsch commented
Did a quick test

2022-10-25 11:17 UTC, merged