chore(CircleCI): split backup from deployment
ParabolInc/parabol pull request #7389
Opened 2022-11-04 10:33 UTC by rafaelromcar-parabol

# Description

Splits the backup from the regular workflow to allow manually running backups and manually deploying to production.

2022-11-04 16:33 UTC, mattkrick commented
love this! haven't tested, but it passes the ocular assessment :wink:

2022-11-07 15:07 UTC, Dschoordsch requested changes

2022-11-08 12:00 UTC, rafaelromcar-parabol commented on .circleci/config.yml
> +          type: approval
Changed. Also added for the backup workflow.

2022-11-09 11:40 UTC, Dschoordsch approved these changes

2022-11-09 11:41 UTC, merged