fix: Organization Image is on top of default
ParabolInc/parabol pull request #7429
Opened 2022-11-14 20:39 UTC by gitstart-parabol

# Description

Fixes #6822
When uploading a profile image for `my organization`, if the image has a transparent background the default is still visible behind. 

## Demo

https://www.loom.com/share/a2845f6db1ec438c829682f2742377a2

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Pull the branch and run the app
  - Got to `me/organizations` url
  - Click on `your user name`s organization
  - Click on the profile photo

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

2022-11-14 20:42 UTC, gitstart-parabol commented on packages/client/components/Avatar/Avatar.tsx
> +  ({sansRadius, sansShadow, hasBorder, picture, size, onClick}) => ({
The `hasBorder` prop is used to indicate whether the profile image should retain its border.

2022-11-14 20:43 UTC, gitstart-parabol commented on packages/client/components/Avatar/Avatar.tsx
> +    border: hasBorder ? '4px solid #B6AEC6' : undefined,
The border hex code was gotten from the placeholder image so it can retain a similar border.

2022-11-14 20:45 UTC, gitstart-parabol commented
@igorlesnenko this PR is ready for review

2022-11-28 10:18 UTC, igorlesnenko requested changes
Now we have a double border on the default image:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/466991/204252626-ead4b4b9-efaa-43b2-8db9-1ef4c7d6fb15.png">

Because image itself has a border, and we add an additional border.

2022-11-28 10:25 UTC, igorlesnenko requested changes
Actually, I suggest to remove this manually added border at all. 

Reasons:
- We don't have it elsewhere around the organization image in the app, why add this on that particular screen?
- Matching it manually with the image is fragile, what if we change the default image later? Ideally, this shouldn't be a part of the default image too, but made with css.
- We currently does not show a border anyway if you upload a non transparent image. So it is a new change introduced rather than a fix.

cc @acressall

2022-11-29 16:50 UTC, igorlesnenko commented
> @igorlesnenko are we cropping it do be a circle? 

We crop it only using CSS:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/466991/204588716-b0ac43fa-95e1-4a0c-81fd-656a2fc80716.png">

> . Do you think we should make the background round, so it would be a closer design to the profile settings?

Do you mean organization page on my screenshot above? Yes, I think it would be more consistent to make it round there too.
Yes, this would be a CSS change

> My only issue is that the white background is a square, so it might be confusing without the border to show you where it will be cropped.

Make sense.
What if we add some shadow? This will work both with default avatar and any uploaded avatar. Could this be a solution?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/466991/204590706-bc7c9cd7-0563-4a57-aeed-9c386e960fad.png">

2022-12-07 17:35 UTC, acressall commented
Looks good @igorlesnenko! Let's make it round and add the shadow

2022-12-15 17:17 UTC, igorlesnenko requested changes
Looks good! Just one more small fix:

When applying the shadow to the default avatar, there is a weird sub-pixel appears

<img width="150" alt="image" src="https://user-images.githubusercontent.com/466991/207922658-84610676-930d-409a-9fbf-fbf62acd0b1d.png">

<img width="87" alt="image" src="https://user-images.githubusercontent.com/466991/207922620-dcf2d51b-bcd0-46fe-ab5b-4bac81444d81.png">

Maybe we can use some lighter shadow color like '#DADADA' ?

2022-12-16 09:46 UTC, gitstart-parabol commented
@igorlesnenko  Please re-evaluate, review suggestions have been implemented.

2022-12-16 14:54 UTC, Dschoordsch approved these changes

2022-12-16 14:54 UTC, merged