Feat(ai-summary): add topic summary to discussion thread
ParabolInc/parabol pull request #7545
Opened 2022-12-08 19:25 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/7472

Demo: https://www.loom.com/share/1512b7ca727548138e492bb864af7d37

### To test

- [ ] Make sure that you've added the `OPEN_AI_API_KEY` and `OPEN_AI_ORG_ID` env vars
- [ ] Add the aiSummary feature flag to your user
- [ ] Create a retro that includes groups with several reflections as well as groups with just one reflection
- [ ] See that the discussion thread includes a comment from Parabol AI that summarises the topic for groups with two or more reflections
- [ ] If a group only has one reflection, there is no topic summary

2022-12-08 21:07 UTC, nickoferrall commented on packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
> +                  style={explainationStyle}
I've moved this around as I think the explanation sentence should come before the topic & discussion summary titles

2022-12-12 11:10 UTC, igorlesnenko approved these changes
Looks good!

2022-12-14 10:00 UTC, Dschoordsch requested changes
Not as part of this PR, but I think we need to tune in the AI query. At the moment it seems it's oversimplifying too much
![Screenshot from 2022-12-14 10-58-45](https://user-images.githubusercontent.com/7331043/207565126-8c1aff70-0dc4-490b-b3ee-3beeabd669ec.png)

2022-12-14 10:00 UTC, Dschoordsch commented on packages/server/postgres/migrations/1670438374119_addAIUser.ts
> +  const picture = 'https://action-files.parabol.co/static/favicon.ico'
+1 If you find out how to gain access, could you please also update the picture of `aGhostUser`?
https://github.com/ParabolInc/parabol/blob/db6909c09d2f0ea3518481bc9612fbc686ae6c56/packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts#L56

2022-12-14 11:47 UTC, nickoferrall commented
Completely agree about fine-tuning it. I've created an issue: https://github.com/ParabolInc/parabol/issues/7569

2022-12-14 12:12 UTC, Dschoordsch approved these changes

2022-12-14 12:13 UTC, Dschoordsch commented
I think even before we go full fledged custom model, we should play around with the summary request and maybe exchange "to a second grade student" with something else. Or just go "TL;DR"

2022-12-14 12:36 UTC, nickoferrall commented
> I think even before we go full fledged custom model, we should play around with the summary request and maybe exchange "to a second grade student" with something else. Or just go "TL;DR"

Yeah, I think it would be a good thing to A/B test. We could implement the up/down arrows (mentioned in https://github.com/ParabolInc/parabol/issues/7569) and see which prompts & text inputs get the best results

2022-12-14 12:36 UTC, merged