fix: emoji length check
ParabolInc/parabol pull request #7578
Opened 2022-12-15 11:38 UTC by nickoferrall

Fix: https://github.com/ParabolInc/parabol/issues/7577

2022-12-16 12:59 UTC, igorlesnenko requested changes
Looks like it works on frontend but not backend, I can type 2 fire emoji, but can't save


https://user-images.githubusercontent.com/466991/208103655-5c999c18-ccba-432c-b328-e2e3cc5ff077.mov

2022-12-19 20:31 UTC, igorlesnenko requested changes
I have my branch updated, but still can't save two emoji. What am I doing wrong?

https://user-images.githubusercontent.com/466991/208515687-bcaee2f8-74e1-4460-8d01-ce6c6d718ec5.mov

2022-12-19 20:37 UTC, igorlesnenko approved these changes
Some glitch on my side, code was not refreshed! Works now!

2022-12-20 11:40 UTC, Dschoordsch approved these changes

2022-12-20 12:04 UTC, merged