feat: PARA-7662 - SAML UI: enable SAML dialog
ParabolInc/parabol pull request #7788
Opened 2023-02-17 12:28 UTC by gitstart-parabol

# Description
Feat #7662

## Demo 
https://user-images.githubusercontent.com/34602861/217807491-d17b5084-5e6b-416f-9f5e-e5232e5e516e.mov

## Test cases. 
- [X] Verify that when the Organization has `verifiedDomains` and the the feature flag `SAMLUI` is set on the org, then the state of the dialog box becomes `enabled`
- [X] Verify that when the state of the dialog box is enabled, we have the label, ` SSO is enabled `
- [X] Verify that when the state of the dialog box is enabled, there a green colored pass mark adjacent to the label `SSO is enabled`
- [X] Verify that when the state of the dialog box is enabled, the current related data appears as shown below
![image](https://user-images.githubusercontent.com/32229780/216897387-cc9d97d4-e5f0-43ca-b8dd-8a2154881fb3.png)
- [X] Verify that this page is mobile responsive and page content looks as shown below on mobile screen
![image](https://user-images.githubusercontent.com/32229780/216897831-6f0e41f7-7837-471b-b617-74da9d62c702.png)
- [X] Verify that  SAML information if filled by only  `billing member `

2023-04-27 10:06 UTC, gitstart-parabol commented
@igorlesnenko this PR is ready for review

2023-05-02 22:54 UTC, mattkrick requested changes
Looking good! Just a couple small changes

2023-05-02 22:54 UTC, mattkrick commented on packages/client/modules/userDashboard/containers/OrgAuthentication/OrgAuthenticationRoot.tsx
> +    <Suspense fallback={renderLoader({Loader: <div />})}>
+1 no need for renderLoader call here, what error were you seeing with just rendering an empty string?

2023-05-02 22:54 UTC, mattkrick commented on packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
> +import OrgAuthenticationSSOEnabled from './OrgAuthenticationSSOFrame'
-1 import name should try to match match the file name if possible

2023-05-02 22:54 UTC, mattkrick commented on packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
> +  const {onError, onCompleted, submitMutation, submitting} = useMutationProps()
-1 we'll need to also grab `error` and show that in an error message. For example, if the metadata is invalid, we'll watch to validate it on the server & then show a message that it is invalid here

2023-05-02 22:54 UTC, mattkrick commented on packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSSOFrame.tsx
> +  samlInfo:
+1 could we use a relay fragment here instead of manually typing out what we expect?

2023-05-05 10:16 UTC, gitstart-parabol commented
> Looking good! Just a couple small changes

Thanks for the feedback @mattkrick, your comments have been implemented.

2023-07-06 22:38 UTC, mattkrick commented
Hi! Thank you for contributing to our app! We're closing this PR due to inactivity, but that doesn't mean the end of the code! This is still a useful feature & if we prioritize it in an upcoming sprint we will use this PR as a reference point.

2023-07-06 22:38 UTC, closed without merging