feat(checkout-flow): add teams limit warning
ParabolInc/parabol pull request #7879
Opened 2023-03-07 20:11 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/7692

In this PR, I'm using the UI that we have in Insights as I think we should be consistent with the UI & messaging.

Org with the `scheduledToLock`:
![warning-1](https://user-images.githubusercontent.com/39854876/223540606-21f0672f-8b40-4dd6-b22a-0781110ddf43.png)

Org with the `lockedAt`:
![warning-2](https://user-images.githubusercontent.com/39854876/223540633-4df586c3-a745-4036-afbf-a724c71b9dd5.png)

### To test

- [ ] View the billing page for an org that has the `scheduledToLock` field and see that the warning UI is the same as Insight
- [ ] View the billing page for an org that has the `lockedAt` field and see that the warning UI is the same as Insight
- [ ] Usage Stats page still works as it did previously
- [ ] The warning message UI looks good

2023-03-07 20:16 UTC, nickoferrall commented
Hey @acressall, what do you think of the UI in the screenshots in the PR description?

I've used the same UI as Usage Stats as I think it makes sense for the UI & messaging to be consistent in both places. That means there are two changes:

1. It doesn't include the cute lil bird in an egg emoji. We could add this in although the tone of the message might conflict with the emoji
2. The copy is slightly different. I like the way the Usage Stats UI specifies why the org/domain is over the Starter tier limit

2023-03-07 21:11 UTC, acressall approved these changes
Makes sense to keep the copy consistent! 👍

2023-03-09 05:46 UTC, igorlesnenko requested changes

2023-03-09 05:46 UTC, igorlesnenko commented on packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
> +        <LimitExceededWarning organizationRef={organization} />
-1 The warning is always shown, even if the limit is not exceeded

2023-03-09 15:29 UTC, igorlesnenko approved these changes

2023-03-09 16:39 UTC, merged