Chore: improve rate limit error handling
ParabolInc/parabol pull request #8201
Opened 2023-05-16 14:18 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/8200

The Sentry error logs suggest it's an axios error. By sending the `data.error` to Sentry, we should be able to find out if it's an RPM or TPM limit.

I haven't included testing steps in this PR as I'm not sure how you can test it unless you hit a 429 error.

2023-05-18 16:35 UTC, nickoferrall commented on packages/server/utils/OpenAIServerManager.ts
> +      if (e instanceof Error) {
The current Sentry error logs include a ton of info, but not much of it is useful other than the 429 error. It looks like an axios error where we should be able to get more valuable info from that response data. OpenAI says their error response specifies the type of 429 error, so I suspect we can find it in that response data. 

Here are the Sentry logs: https://parabol.sentry.io/issues/3912924421/events/?project=107196&referrer=issue-stream&statsPeriod=14d&stream_index=0

2023-05-22 16:26 UTC, Dschoordsch requested changes

2023-05-22 16:26 UTC, Dschoordsch commented on packages/server/utils/OpenAIServerManager.ts
> +          sendToSentry((e as AxiosError).response?.data?.error)
-1 I assume `.error` is a string message and should be wrapped in an error, right?

2023-05-22 16:26 UTC, Dschoordsch commented on packages/server/utils/OpenAIServerManager.ts
> +      const error = new Error('OpenAI failed to getSummary')
+1 It would be nice to have the short branch first with an early return, or an else here.

2023-05-24 15:16 UTC, nickoferrall commented
Having spent more time digging through the OpenAI community support pages, I haven't seen any evidence of more detailed logs available than the "Too many requests" error that we can currently see in Sentry (see [here](https://parabol.sentry.io/issues/3912924421/events/25340a1c0fe94062b30ba08d83cdf390/?project=107196)), so I'll close this PR.

It's still unclear whether we're hitting a token per minute limit (TPM) or a rate per minute (RPM) limit. Hopefully, we can find this out by:
- Looking at the frequency of usage of the API. If we're sending more than 3,000 requests per minute (the davinci limit [here](https://platform.openai.com/account/rate-limits)), we know it's a RPM limit. We should be able to see this in OpenAI's usage page ([here](https://platform.openai.com/account/usage)), but it's broken at the moment, saying "temporarily unavailable".
- Looking into our own meeting data to see how many summaries were created during a minute where we have a Sentry error. 
- Changing `max_tokens` [here](https://github.com/ParabolInc/parabol/pull/8267). If it results in significantly less 429 errors, we know it was a TPM problem.

I sent a request to OpenAI to increase our limits last week. They say they usually take 7-10 business days to respond, so we should hear from them this week or next.

2023-05-24 15:16 UTC, closed without merging