feat(share-summary): Add share topic button to meeting summary
ParabolInc/parabol pull request #8331
Opened 2023-06-06 13:31 UTC by igorlesnenko

Partially solves: #8232 #8234

**Demo**

https://www.loom.com/share/1302d78b31494ff8a02a20d6f8790a4d

**In this PR**

- Added `share topic` to the email summary (works both in the email and the website)
- Button opens a modal (Added routing and modal placeholder)

**Not included**

- Modal UI
- I have some scroll issue when modal is opened, going to look into it in next PR

**How to test**

- Add `shareSummary` org-level feature flag
- Run a retro and have some topics
- Click on `Share topic` button, see modal is opened and routing works fine
- Click on `Share topic` button from email, see modal is opened and routing works fine

2023-06-08 09:38 UTC, nickoferrall requested changes
When I end the meeting, I'm getting the following error in the console:
```
10:19:44 1|GraphQL Executor | TypeError: Cannot destructure property 'history' of '(0 , hooks_useRouter\_WEBPACK_IMPORTED_MODULE_5__.default)(...)' as it is undefined.
```
I also don't receive the email confirmation. When I remove the feature flag and end the meeting, I do receive the email confirmation.

2023-06-08 09:38 UTC, nickoferrall requested changes
When I end the meeting, I'm getting the following error in the console:
```
10:19:44 1|GraphQL Executor | TypeError: Cannot destructure property 'history' of '(0 , hooks_useRouter\_WEBPACK_IMPORTED_MODULE_5__.default)(...)' as it is undefined.
```
I also don't receive the email confirmation. When I remove the feature flag and end the meeting, I do receive the email confirmation.

2023-06-08 19:43 UTC, nickoferrall approved these changes
LGTM! Nice job getting it working from the email too

2023-06-14 09:44 UTC, igorlesnenko commented on packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
> +  /* eslint-disable react-hooks/rules-of-hooks */
Was not sure about it, as I will have to create 3 components just to workaround this case

2023-06-14 13:25 UTC, Dschoordsch requested changes
Scrolling behaves weird when cancelling and then reopening the dialog after having scrolled
![Peek 2023-06-14 14-58](https://github.com/ParabolInc/parabol/assets/7331043/bbc3b2c5-0594-45e2-b268-ce386e3c0016)

2023-06-16 17:14 UTC, igorlesnenko commented
@Dschoordsch I made a partial fixes for this. Scroll to top issue is related to routing. Was not able to find a quick solution yet. I probably need to save scroll position or show popup using `useState`. Can I look into in in some next PRs?

2023-06-19 13:56 UTC, igorlesnenko commented
@Dschoordsch fixed by changing approach for showing modal window from browser

2023-06-20 09:00 UTC, Dschoordsch requested changes

2023-06-20 09:00 UTC, Dschoordsch commented on packages/client/hooks/useModal.ts
> +    allowScroll: false
-1 Scrolling is broken on unrelated modals with your pr.
master:
![master](https://github.com/ParabolInc/parabol/assets/7331043/bfa8928f-355b-45d6-bdd2-10ed051d8f83)
this pr:
![pr](https://github.com/ParabolInc/parabol/assets/7331043/2818ebf7-22e3-4481-82fe-8e7ab02483b8)
Not sure if it's related to this line and I stopped checking after I found the first issue.

2023-06-27 11:15 UTC, merged