feat/teamFilterInTimeline
ParabolInc/parabol pull request #8521
Opened 2023-07-16 01:40 UTC by tianrunhe

- Add team filter in timeline history
- Fix margin right
- Clean up some code

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2023-07-18 10:17 UTC, nickoferrall approved these changes

2023-07-18 10:17 UTC, nickoferrall commented on packages/server/graphql/getValidTeamIds.ts
> +  if (teamIds?.length) return teamIds!.filter((teamId) => tms.includes(teamId))
+1 this isn't your code, but we can remove the `!` from `teamIds!` as we're checking if `teamIds` exists

2023-07-18 10:17 UTC, nickoferrall commented on packages/server/graphql/getValidTeamIds.ts
> +  // the following comments can be removed pending #4070
+1 what's #4070 referring to? This: https://github.com/ParabolInc/parabol/issues/4070? 

If so, it looks like we can remove the commented lines

2023-07-19 14:11 UTC, Dschoordsch requested changes
Only a naming issue, otherwise looks good!
Feel free to merge when fixed.

2023-07-19 14:11 UTC, Dschoordsch commented on packages/server/graphql/getValidTeamIds.ts
> +export const getValidTeamIds = async (
-1 `getAccessibleTeamIds` or `filterByTeamMemberIds` would be more descriptive. All input ids could be "valid" in other contexts.

2023-07-19 14:11 UTC, Dschoordsch commented on packages/server/graphql/getValidTeamIds.ts
> +  // filter the teamIds array to only teams the user has a team member for
+1 this could be the function comment

2023-07-20 06:27 UTC, Dschoordsch approved these changes

2023-07-20 17:15 UTC, merged