chore(share-summary): add utm params and reflectionGroupId param
ParabolInc/parabol pull request #8522
Opened 2023-07-17 09:23 UTC by igorlesnenko

added utm params and reflectionGroupId to the segment event

**How to test:**

- Add shareSummary org-level feature flag
- Run a retro and have some topics
- Click on Share topic button
- Share some topic
- Check that segment event is sent correctly
- Check that shared slack message has UTM params in its links

2023-07-17 18:03 UTC, tianrunhe approved these changes
Tested and worked!

2023-07-17 21:26 UTC, tianrunhe requested changes
Per discussion [here](https://parabol.slack.com/archives/C042E8PGPD4/p1689629079376109?thread_ts=1689627498.823759&cid=C042E8PGPD4), we should change `utm_campaign = 'sharing'` in the [summary email](https://github.com/ParabolInc/parabol/blob/5ff6150290a113bc3ab24aedd5896c0b70470698/packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx#L100) too

2023-07-18 08:59 UTC, igorlesnenko commented
@tianrunhe share topic button in email had no utm params at all, I added them. If I undserstand correctly, I don't need to change other summary email links

2023-07-18 17:35 UTC, tianrunhe approved these changes

2023-07-18 17:44 UTC, merged