feat: show all teams within domain
ParabolInc/parabol pull request #8554
Opened 2023-07-20 18:32 UTC by nickoferrall

Fix: https://github.com/ParabolInc/parabol/issues/8483

Demo: https://www.loom.com/share/edaf3ff794714b249b17a3835ef55623

If this PR is approved, I'll create a Notion doc with an example mutation, and let the sales team know. 

### To test

- [ ] Add the `canViewTeamsInDomain` and `checkoutFlow` user feature flags
- [ ] Go to the Teams view of an org where you're the billing leader
- [ ] See that all teams within the domain are visible
- [ ] You can filter to see all teams within org
- [ ] Users without the `canViewTeamsInDomain` can only see teams within their org and don't see the filter menu

2023-07-20 18:37 UTC, nickoferrall commented on packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
> +  const ALL_TEAMS_IN_ORG = `All Teams In ${name}`
Originally, I added these labels to `FilterLabels` in `constEnums`, but I think we should show the org/domain name, so I'm instantiating them here

2023-07-20 18:37 UTC, nickoferrall commented on packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
> +              defaultActiveIdx={label === ALL_TEAMS_IN_DOMAIN ? 0 : 1}
If we turn on the feature flag, I assume we'll be directing users to the teams within the domain, so I chose this as the default active index

2023-07-20 18:39 UTC, nickoferrall commented
Hey @acressall, it'd be great to get your eyes on the design 🙏  I went with a filter menu instead the switch button I suggested in the issue because I think it's more consistent with our design, and we already have a dropdown menu built

2023-07-20 19:18 UTC, acressall approved these changes
Filter is a good choice!

2023-07-24 15:30 UTC, igorlesnenko commented on packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
> +    (label === ALL_TEAMS_IN_DOMAIN && canViewTeamsInDomain ? teamsByDomain : teams) ?? []
There is a rare edge case. If rename org to `parabol.co`, toggle breaks so I can't switch it.

2023-07-24 18:11 UTC, nickoferrall commented
Updated! I was able to see the teams when you couldn't because I had `insights` turned on which meant `suggestedTier` was true for me: https://github.com/ParabolInc/parabol/blob/74b7e46b72637a0a3cc7c9c5c349b1f7e0249a49/packages/server/graphql/public/types/User.ts#L62

I'm now querying the data from the `company` field rather than `domains`, so you should be able to see it now 👍

2023-07-25 08:39 UTC, igorlesnenko requested changes
I have a team that in example.com domain

But it shows a teams from parabol.co domain

<img width="1015" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/286e85de-f47f-47b2-bebc-f9000fd322f0">

<img width="1008" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/2f1187b1-a0ce-4fa6-a4dd-2bc795e6096b">

2023-08-09 07:16 UTC, igorlesnenko requested changes
If I now go to my example.com org, I don't see any filter anymore

<img width="1010" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/69f5e2c3-597f-4dbe-8d10-a51562300bca">

2023-08-09 07:30 UTC, igorlesnenko approved these changes
As far as I understand if my own domain is different from org domain, I can't see the filter now

2023-08-09 08:34 UTC, nickoferrall commented
> As far as I understand if my own domain is different from org domain, I can't see the filter now

Yep, exactly. Your domain is `parabol.co` so `company.organizations` will only return the orgs in your `parabol.co` domain (see [here](https://github.com/ParabolInc/parabol/blob/0f638bcce554c7adea5ac07043d3d7f373a0250b/packages/server/graphql/public/types/Company.ts#L21)). 

If you have the `canViewTeamsInDomain` feature flag, you can go to `Parabol Org` and see all the teams in the org & the domain.

If you go to `Example Org` created by someone with the `example.com` domain, you shouldn't be able to view all the teams in that domain, so I'm hiding the filter.

2023-08-09 22:31 UTC, mattkrick commented on packages/server/graphql/public/types/Company.ts
> +  const viewer = await getUserById(viewerId)
+1 how can i test this? to fetch `{viewer { company { id } }` we already have to get the viewer, so I'm not sure why it's needed? if it is needed, could we use the dataloader to reduce a fetch?

2023-10-20 13:46 UTC, closed without merging