chore: Build once, run everywhere
ParabolInc/parabol pull request #8557
Opened 2023-07-21 21:45 UTC by mattkrick

# Description

fix #8101

In the near future, every PPMI will use the same docker image. The only difference between deploys will be environment variables. That means we need to remove ENV vars from the build step.

The last remaining env var that exist in the build step is CDN_BASE_URL.

We can achieve this in 1 of 2 ways:
-  create a predeploy step that rewrites our client assets with a different CDN that each PPMI can call
- force every instance to use the same `publicPath` and if a client wants to use a CDN, they may do so behind their own reverse proxy.

I built both, but decided to go with the second option because it is simpler, removes all CORS problems, and allows for additional caching between version bumps.

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2023-08-02 22:10 UTC, mattkrick commented on static/images/brand/mark-cropped-192.png
chrome kept giving me an error saying our pics were off by 1 pixel so i fixed that here

2023-08-07 17:22 UTC, igorlesnenko requested changes
I see few places where URLs are hardcoded. Should we change them or remove if it is legacy?

https://github.com/ParabolInc/parabol/blob/b656e7d44061aabd78abadfb05e79d61de9bd181/packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx#L58

https://github.com/ParabolInc/parabol/blob/6c88e71f2bb11d4966c3b23c7a49144e9eb69782/.circleci/config.yml#L306-L314

https://github.com/ParabolInc/parabol/blob/69cad570a630f877f2f01aea79cd7fdd1431fb39/packages/client/types/constEnums.ts#L125-L126

https://github.com/ParabolInc/parabol/blob/f3361ab138d76ecbd2fa233e518790226414709e/packages/client/hooks/useMockPeekers.ts

2023-08-07 20:29 UTC, mattkrick commented on packages/server/utils/StaticServer.ts
> -import PROD from '../PROD'
yes! `PROD` is from back when we didn't use webpack to compile the server. I wanted to do it in this PR, but it's already size L so i decided to do it in the next. Issue here https://github.com/ParabolInc/parabol/issues/8627

2023-08-07 20:30 UTC, mattkrick commented on scripts/toolboxSrc/preDeploy.ts
> -  const envPath = path.join(PROJECT_ROOT, '.env')
yes! we've had that issue open for awhile here: https://github.com/ParabolInc/parabol/issues/8202. I'll be prioritizing that after this PR to keep the size down

2023-08-07 20:33 UTC, mattkrick commented
> I see few places where URLs are hardcoded. Should we change them or remove if it is legacy?

Yes! We'll be getting rid of those next. https://github.com/ParabolInc/parabol/issues/8549

2023-08-07 20:42 UTC, mattkrick commented on scripts/toolboxSrc/preDeploy.ts
> +  await new Promise((resolve) => setTimeout(resolve, 50))
comment added!

2023-08-08 15:53 UTC, igorlesnenko approved these changes

2023-08-10 18:25 UTC, merged