chore(gcal): implement oauth
ParabolInc/parabol pull request #8594
Opened 2023-07-28 15:52 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/8530

Demo: https://www.loom.com/share/f82541b86a9b49fe8ac0873fb49cffe6

### To test

- [ ] Add the gcal user feature flag
- [ ] Add the `GCAL_CLIENT_ID` and `GCAL_CLIENT_SECRET` from the devops repo [here](https://github.com/ParabolInc/action-devops/blob/9cdf05e87e8ed9235f306a592ffef911b318ff0a/environments/local#L25-L26)
- [ ] Run `yarn build` then `yarn predeploy` to run `primeIntegrations`
- [ ] Can add & remove the gcal integration 
- [ ] Can create a gcal event in your calendar after integrating

2023-08-03 13:07 UTC, igorlesnenko approved these changes
Works! But some clean up required before merging.

2023-08-07 19:00 UTC, mattkrick commented
Q: Can we get away with fewer permissions? Feels like the ability to delete someone's calendar is a bit of an overreach
![image](https://github.com/ParabolInc/parabol/assets/5514175/321b5247-ab8a-4912-9052-6abca65eba19)

2023-08-07 19:09 UTC, mattkrick commented
Everything works! There are a couple UI kinks, but nothing blocking merge:
- Let me uncheck the box by clicking the label
- Show me an error message if you can't create the Gcal event
- Use calendar/time picker for dates (can kick this back to another date)

Loom here describing them: https://www.loom.com/share/025b4d6d67734a52afab73c04ddfdb21

2023-08-07 19:10 UTC, mattkrick requested changes
Very minor code stuff! Perms may be an issue, up to you when to fix

2023-08-09 15:24 UTC, nickoferrall reviewed
Updates:

- [ ] Refactored to sdl pattern
- [ ] You can check the checkbox by clicking on the label
- [ ] Created a GH issue for handling the error state here https://github.com/ParabolInc/parabol/issues/8635. This is just for internal testing so we can ship this PR without that. I also have a GH issue for improving the date UI & UX: https://github.com/ParabolInc/parabol/issues/8575
- [x] Reduced the amount of permissions we request 

![Screenshot 2023-08-09 at 14 37 00](https://github.com/ParabolInc/parabol/assets/39854876/65dda96a-d0e9-44db-a031-0414ca1d9b2a)

2023-08-09 19:32 UTC, mattkrick approved these changes
awesome! love the smaller scope. 1 itty bitty fixup & then feel free to merge

2023-08-09 19:32 UTC, mattkrick commented on packages/server/graphql/public/typeDefs/TeamMemberIntegrations.graphql
> +type TeamMemberIntegrations {
+1 Could you please remove `type TeamMemberIntegrations` from `_legacy.graphql` now that it lives in its own home?

2023-08-10 10:33 UTC, merged