chore: Cleanup old starter tier organizations
ParabolInc/parabol pull request #8617
Opened 2023-08-03 20:53 UTC by tghanken

Fixes #8507 

When we changed the names of our plan tiers in #7505, there were two organizations created while the migration `20221220161224-updateTier.ts` was running that are left with the old `personal` tier name.  This migration cleans up those tier values, and migrates them to the new `starter` tier name.

2023-08-03 20:54 UTC, tghanken commented on packages/server/database/migrations/20230801200811-fixOrganizationTier.ts
> +  // noop
Didn't implement a `down` function, as any cleanup should be handled by `20221220161224-updateTier.ts`.

2023-08-07 10:28 UTC, nickoferrall approved these changes
As this is scanning through all Organizations, and Rethinkdb is so brittle, we might need to batch the query. I'll remove the One Review Required label and tag Matt to see what he thinks.

2023-08-07 10:33 UTC, nickoferrall requested changes
As this is scanning through all Organizations, and Rethinkdb is so brittle, we might need to batch the query. I'll remove the One Review Required label and tag Matt to see what he thinks.

Before doing that, it looks like the Build & PR Title checks are failing. The build says:
```
    if (files.length !== 154) throw new Error('New migrations must live in the postgres/migrations directory')
```

although this is a Rethinkdb migration 🤔 Once those are fixed, we can move this to Maintainer Review.

2023-08-07 10:55 UTC, igorlesnenko commented
@nickoferrall now we are storing all rethink migrations as PG migrations. Here is the example:
https://github.com/ParabolInc/parabol/blob/7991c595c31b973dbbf621b5b86bdbaa0fd994c7/packages/server/postgres/migrations/1676341596550_updateOrgIdOnSAML.ts

2023-08-07 15:44 UTC, tghanken commented
> As this is scanning through all Organizations, and Rethinkdb is so brittle, we might need to batch the query. I'll remove the One Review Required label and tag Matt to see what he thinks.

Interesting!  My intuition from using other DB systems is that with a highly selective predicate, it's better to just issue one query and let the query planner handle it, but happy to batch this if it makes sense!  Alternatively I could filter for the two orgIds we care about, but that makes this somewhat less flexible.

2023-08-07 15:57 UTC, nickoferrall approved these changes
LGTM! I'm probably overly anxious and it doesn't need to be batched, but I think it's worth going through Maintainer Review to be sure

2023-08-07 17:31 UTC, mattkrick commented
LGTM!

2023-08-07 17:31 UTC, merged