chore: active plan visual cue
ParabolInc/parabol pull request #8637
Opened 2023-08-09 15:54 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/8628

Loom demo: https://www.loom.com/share/bbfd53b43b59418eb152321be0023a14

### To test

- [ ] Click "Select Plan" and see that the plan's border is now outlined, indicating that it's active

2023-08-09 17:11 UTC, acressall requested changes
See comment on Loom

2023-08-10 08:04 UTC, igorlesnenko commented
Agree, we need to change button text too, maybe even a color

2023-08-10 17:39 UTC, nickoferrall commented
Makes sense! Here's the update: https://www.loom.com/share/7a4f3ccd980e4c2d852ee5105ba7f24d

2023-08-10 18:14 UTC, acressall approved these changes

2023-08-11 08:14 UTC, igorlesnenko approved these changes

2023-08-11 08:41 UTC, merged