feat(standups): rich text in slack notifications
ParabolInc/parabol pull request #8715
Opened 2023-08-22 19:14 UTC by BartoszJarocki

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2023-08-23 07:24 UTC, BartoszJarocki commented
@jmtaber129 @mattkrick there are at least two possible solutions

First of all, tiptap does not support providing output as markdown, which is what slack supports. that leaves us two options

1. Quick, just like the example implementation in this PR - ie. add a [turndown library that converts HTML to markdown]([mixmark-io/turndown: 🛏 An HTML to Markdown converter written in JavaScript](https://github.com/mixmark-io/turndown)) and just use it

Pros:
- quick, and in theory configurable with plugins (ie. we could still implement mentions etc)

Cons
- for example html headers won't be displayed in slack `section` component that we use to format notifications, so it looks like that
<img width="581" alt="Screenshot 2023-08-23 at 09 12 03" src="https://github.com/ParabolInc/parabol/assets/1017620/a4261fd1-7155-419a-8fd4-0546aa8b09b9">

we could still override the conversion made by this library and just make the headers bold or something like that.
 
2. Do the conversion ourselves, this gives us more flexibility 

Pros
- we can split the message into multiple slack blocks and use not only markdown section, but also headers etc. 
- more flexibility 

Cons
- more time consuming 

any thoughts? If the priority is to ship fast, we can try to tweak he library, if we can spend a little bit more time, we can provide our own implementation that'd be more future proof.

2023-08-23 14:12 UTC, BartoszJarocki commented
decode do go with custom impl, I don't want to spend any time fixing external library quirks 🤷‍♂️

2023-08-24 08:08 UTC, BartoszJarocki commented
@jmtaber129 do you mind taking a look?

2023-08-24 18:07 UTC, mattkrick commented on packages/server/utils/tiptap/convertToMarkdown.tsx
> +const tiptapNodeHandlersLookup: {[type: string]: (node: JSONContent, depth?: number) => string} = {
+2 50 LOCs & no external deps? pretty sweet!

2023-08-24 18:13 UTC, mattkrick commented
I absolutely love your solution, smaller bespoke packages always get my vote.
curious, did you check out https://github.com/aguingand/tiptap-markdown? it's sooo much larger than your solution, so i was wondering what extra functionality it might give?

2023-08-25 02:47 UTC, jmtaber129 requested changes
Code looks good, and really nice approach! Just a few unsupported nodes+marks things:

-1 Mentions aren't supported - If I mention a user, nothing appears where their name is
-1 Inline code snippets like `these` appear as plaintext
+1 The horizontal rule (`<hr/>`) nodes aren't included - this isn't too important (we didn't _really_ support these until last week) and there's not a super elegant way to handle this without switching this approach to pure slack blocks (or refactor the recursive solution to an iterative one) AFAIK, but we could insert a line like `--------` just to show that the response had some form of horizontal divider.
+1 Quote blocks - our CSS basically just indents with no other styling when a user inserts a quote block (i.e. what you get with a `>` in slack), but it would be nice to include support for this in slack anyway.

2023-08-25 11:39 UTC, BartoszJarocki commented
@jmtaber129 thanks for pointing these out! 

1. mentions - I've added support to just display it like a normal text - here's an example 
<img width="347" alt="Screenshot 2023-08-25 at 13 37 28" src="https://github.com/ParabolInc/parabol/assets/1017620/b11730ee-b911-440c-9380-359ac81c0491">
to make it a real mention, we'd need to map Parabol user id into Slack user id. at this point I'm not sure of the effort needed to to that, but I'd suggest merging it as is and handling this as a separate issue (as this is a big improvement over existing functionality already). 

2. inline code - added!

3. horizonal rule, how can I add that to our standup response so I can test? 😅 

4. black quotes - added!

2023-08-25 14:47 UTC, BartoszJarocki commented
@jmtaber129 added support for horizontal lines too. it'll be just `---` as Slack does not seem to support it. 
<img width="589" alt="Screenshot 2023-08-25 at 16 46 58" src="https://github.com/ParabolInc/parabol/assets/1017620/fbfe8bcd-6ae2-4df0-b3be-0abfa6b93122">

can you take a look again?

2023-08-28 16:01 UTC, jmtaber129 approved these changes
One small change needed to fix mentions, otherwise LGTM

2023-08-29 10:00 UTC, BartoszJarocki commented on packages/server/utils/tiptap/convertToMarkdown.tsx
> +    return `<@${label}>`
fixed. it required a little bit of investigation as it turns out Slack tries to [automatically parse mentions, links etc. ](https://api.slack.com/reference/surfaces/formatting#automatic-parsing__disabling-automatic-parsing)

2023-08-29 10:01 UTC, BartoszJarocki commented
@mattkrick do you mind taking a final look? thanks!

2023-09-05 21:50 UTC, merged