feat: invite link in right drawer
ParabolInc/parabol pull request #8806
Opened 2023-09-08 15:41 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/8753

Demo: https://www.loom.com/share/49212b2a3b7540d2848f4012ab060c1a

### To test

- [ ] Create a new team and see the right drawer opens with the invite link
- [ ] Create a new org and see the right drawer opens with the invite link

2023-09-08 15:50 UTC, acressall approved these changes

2023-09-11 11:10 UTC, Dschoordsch requested changes
The scrollbar is cut off on initial loading on Safari: <img width="284" alt="Screenshot 2023-09-11 at 12 54 56" src="https://github.com/ParabolInc/parabol/assets/7331043/292317d0-8c31-4411-bfc9-11e01511beb3">

2023-09-11 15:37 UTC, nickoferrall commented on packages/server/graphql/mutations/addTeam.ts
> +          .run()
I like it! That means less code and more visibility. Updated 👍

2023-09-11 15:43 UTC, nickoferrall commented
> The scrollbar is cut off on initial loading on Safari

I am seeing the full scrollbar on initial load in Safari. Are you on linux? 🤔 For me, I think it's a small enough detail that it's OK to merge this PR even if it's not showing up entirely on initial load for everyone 

<img width="274" alt="Screenshot 2023-09-11 at 16 34 54" src="https://github.com/ParabolInc/parabol/assets/39854876/5a570d11-fe94-4fbf-a718-6f893b97fdff">
<img width="282" alt="Screenshot 2023-09-11 at 16 34 33" src="https://github.com/ParabolInc/parabol/assets/39854876/3515b8f6-adc2-43ed-9fd6-7a4594c14cb7">

2023-09-12 14:46 UTC, Dschoordsch approved these changes
I agree it's a small detail and given the small share of users using Safari, that's ok for the first iteration. We should still fix it straight away as the perceived quality is not very good if you see this:

https://github.com/ParabolInc/parabol/assets/7331043/1130ff95-dbc9-4be1-ac94-68780290a3f6

I'm testing on mac

2023-09-12 17:51 UTC, acressall commented
The local version is much longer than what will be in production, right? It looks like this version has `invitation....` included, but in prod it should be `prbl.in/[gibberish]` which is more likely to fit

2023-09-13 08:43 UTC, nickoferrall commented
> The local version is much longer than what will be in production, right?

Yep, that's right. I can see how it looks with the shorter link. I've created an issue 👍

2023-09-13 08:43 UTC, merged