chore(auto-join): verify org founder or billing leads
ParabolInc/parabol pull request #8989
Opened 2023-10-19 16:35 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/8988

### To Test

This is difficult to test! I only have one `parabol.co` email address. Now we require that an org has a valid user identity and email domain, I'm not able to test this perfectly. What I did is:

- [ ] Follow the testing steps in: https://github.com/ParabolInc/parabol/pull/8883
- [ ] Always return `true` from `checkEmailDomain` [here](https://github.com/ParabolInc/parabol/blob/329efd544659424437c20731166324b4db13557d/packages/server/dataloader/customLoaderMakers.ts#L740)

2023-10-20 18:04 UTC, nickoferrall commented
Thanks @Dschoordsch, I've updated the testing steps 👍

2023-10-24 15:18 UTC, Dschoordsch requested changes
I did some [tests](https://github.com/ParabolInc/parabol/pull/9036) and it's failing for an inactive founder.

2023-10-24 15:18 UTC, Dschoordsch commented on packages/server/dataloader/customLoaderMakers.ts
> +export const autoJoinTeamsByValidOrgId = (parent: RootDataLoader) => {
+1 I think it would be fair to still call it `autoJoinTeamsByOrgId`

2023-10-30 13:33 UTC, nickoferrall commented
Thanks for adding the tests! The problem was I was getting the `founder` using: `org('members').filter({inactive: false}).nth(0)`, but I wanted to get the first user and could then check if that user is inactive.

2023-10-30 16:43 UTC, Dschoordsch approved these changes

2023-10-30 16:44 UTC, merged