feat(zoom-transcription): UI improvements
ParabolInc/parabol pull request #8993
Opened 2023-10-20 14:00 UTC by nickoferrall

See @enriquesanchez's comment here with designs: https://parabol.slack.com/archives/C0161UFBM6W/p1697754002870749?thread_ts=1697454762.894489&cid=C0161UFBM6W

Figma [here](https://www.figma.com/file/okoRD7I7lZR08V4Zk7O7G6/random?type=design&node-id=1732-6422&mode=design&t=KNYUoHSHmlsjEiRd-4).

This PR:

- Updates the transcription thread
- Adds the subscription so that all users are updates when someone enters a Zoom link in the input

This PR does not:

- Update the discussion thread header underlining
- Fix the transcription UI. I want to change the way we store the transcription in db first, which I'll do in a separate PR.

![Screenshot 2023-10-20 at 10 16 35](https://github.com/ParabolInc/parabol/assets/39854876/d54c6a2e-536a-4c08-8e88-0ff8bbba7bda)
![Screenshot 2023-10-20 at 10 18 06](https://github.com/ParabolInc/parabol/assets/39854876/5b1feb6a-39ee-4626-bef1-a9a94e6a2084)

### To test

- [ ] Run the `updateOrgFeatureFlag` mutation and add the `zoomTranscription`
- [ ] Create a Retro and see that the UI looks like the images above
- [ ] The UI updates for all meeting members when one meeting member enters the Zoom URL

2023-10-20 16:00 UTC, nickoferrall commented on packages/client/components/RetroDiscussPhase.tsx
> +                        showTranscription={showTranscription}
We no longer need to include `showTranscription`. I removed this in the next PR

2023-10-20 22:20 UTC, enriquesanchez requested changes
This is looking good!

I wasn't able to test this PR because I don't know how to enable feature flags locally 🙈 , but looking at the screenshots you shared I have a couple of requests:

1. Can the description text be darker? Looks like it's set to `Slate 600` and the contrast is pretty low. Can we bump it up to `Slate 700`? The text field placeholder is fine at 600.
2. The button's label looks very small (maybe 12px?), is that the standard button component? There's also a gray border around the button which shouldn't be there.

2023-10-23 10:31 UTC, nickoferrall commented
>  I don't know how to enable feature flags locally

[Here's](https://www.notion.so/parabol/How-to-enable-or-remove-a-user-feature-flag-5c41c2075d9e4eca9b17aa2f4a79ace7) how you can add a feature flag if you'd like to! You'd go to `http://localhost:3000/admin/graphql`. If you can't access that page, then you need to add the super user role (`su`) to your user using pgadmin.

> Can the description text be darker? Looks like it's set to Slate 600 and the contrast is pretty low. Can we bump it up to Slate 700?

It's the same colour as the description text in the empty discussion thread, so we'd need to change the colour for both of them if we want to:

![Screenshot 2023-10-23 at 11 23 50](https://github.com/ParabolInc/parabol/assets/39854876/eb0b5ca8-9207-4a3a-b565-1035f9a1aaf9)
![Screenshot 2023-10-23 at 11 23 42](https://github.com/ParabolInc/parabol/assets/39854876/07d73e5c-8106-4737-a297-04fd3d6341de)


> The button's label looks very small (maybe 12px?), is that the standard button component? There's also a gray border around the button which shouldn't be there.

Thanks, I've removed the border and bumped the font size to the default size:

![Screenshot 2023-10-23 at 11 27 44](https://github.com/ParabolInc/parabol/assets/39854876/c276da8e-a8f9-489a-a770-b30566d43322)

2023-10-23 10:39 UTC, Dschoordsch commented
>If you can't access that page, then you need to add the super user role (`su`) to your user using pgadmin.

It's easier to just run
```
yarn node ./scripts/toolbox/assignSURole.js --add you@example.com
```
to give yourself `su` rights. Don't forget to log out and in again.

2023-10-24 09:48 UTC, nickoferrall commented
> @nickoferrall I'm getting this error while trying to enable the feature flag: "Value \"zoomTranscription\" does not exist in \"UserFlagEnum\" enum.", I'm not sure what I'm doing wrong.

This one is an org feature flag. It looks like you're trying to add a user feature flag. 

> Ah I see. Let's leave it as it is then. I'll revisit text contrast soon.

Sounds good 👍

2023-10-26 08:20 UTC, Dschoordsch approved these changes

2023-10-26 08:20 UTC, Dschoordsch commented on packages/client/components/ZoomSVG.tsx
> +import React from 'react'
+1 Why do we need this in addition to `zoom-logo.svg`?

2023-10-26 08:20 UTC, Dschoordsch commented on packages/client/components/DiscussionThreadListEmptyTranscriptState.tsx
> +})
+1 I don't like that we're introducing more styled components when we're actively trying to get rid of it.

2023-10-30 14:52 UTC, merged