chore: don't lock org in case of failed payment
ParabolInc/parabol pull request #9055
Opened 2023-10-26 08:37 UTC by igorlesnenko

fixes #8341

2023-10-26 14:51 UTC, nickoferrall approved these changes
In the new checkout flow, it doesn't upgrade to team with that card number because of the way we're handling 3D secure cards, but it is no longer locking the org after a failed payment

2023-10-26 16:23 UTC, igorlesnenko commented
> In the new checkout flow, it doesn't upgrade to team with that card number because of the way we're handling 3D secure cards, but it is no longer locking the org after a failed payment

Ah that is fine too I think!

2023-10-27 11:37 UTC, Dschoordsch requested changes
Did not test yet.

2023-10-27 11:37 UTC, Dschoordsch commented on packages/server/billing/helpers/terminateSubscription.ts
-1 As I understand it, we shouldn't delete the subscription if a payment fails, but we still do on l31. I think also the name `terminateSubscription` could be updated to indicate it's not terminating anymore.

2023-10-27 12:26 UTC, igorlesnenko commented on packages/server/billing/helpers/terminateSubscription.ts
@Dschoordsch We still use this function and terminate subscription only in a single case.

If the first payment fails and subscription is in incomplete status.

> After 23 hours subscription updates to incomplete_expired and the invoice becomes void.
> Not to handle this particular case in 23 hours, we do it now

https://github.com/ParabolInc/parabol/pull/9055/files#diff-71929e8c8695ec1c675f137d9b8806bbe9f2b941921f34637902888e0e9c18a4R74-R76

2023-10-30 14:55 UTC, Dschoordsch approved these changes
Works

2023-11-02 15:13 UTC, tghanken approved these changes

2023-11-02 15:56 UTC, merged