chore: fix migraiton conflicts, untested
ParabolInc/parabol pull request #9097
Opened 2023-11-01 21:01 UTC by mattkrick

# Description

The most frequent reason for a failed release is a failed predeploy due to conflicting migration names.
Today, it's possible to merge 2 migration PRs to master. They'll both be passing, master will be passing, but staging will fail because a PR with a newer migration was already pushed to staging/production.

This PR stops that by making sure the PR doesn't include any migrations that predate the latest migration on master.

2023-11-02 11:16 UTC, Dschoordsch approved these changes
This will only catch some of the cases. If I have 2 PRs with conflicting migrations, both will pass the build pre-merge, but might cause an issue post merge as they're not re-verified after each master change.
I think we could only reliably check this on master post-merge.

2023-11-02 11:16 UTC, Dschoordsch commented on .github/workflows/build.yml
> +          fi
+1 I'm not a fan of this restriction. If you know the number of migrations, you can do
```
FIRST_NEW_MIGRATION=$(ls packages/server/postgres/migrations | tail -n $NEW_MIGRATION_COUNT | head -n1)
```

2023-11-02 12:05 UTC, Dschoordsch requested changes
After thinking about it, I think I would prefer if we could just check master that it's in the correct order. I think something along the lines of this
```bash
#!/bin/bash

PREV_COMMIT=$(git rev-list HEAD | tail -n 1)
PREV_FILE=''
for F in packages/server/postgres/migrations/*.ts; do
  CURR_COMMIT=$( git log --diff-filter=A --pretty=format:"%H" -- "$F")
  git merge-base --is-ancestor $PREV_COMMIT $CURR_COMMIT > /dev/null
  if [ $? -ne 0 ]; then
    echo "$PREV_FILE was added after $F but has a smaller timestamp"
  fi
  PREV_COMMIT=$CURR_COMMIT
  PREV_FILE=$F
done
```
This needs some cleanup though, or we make sure to only consider all files after the last failure

2023-11-02 19:36 UTC, mattkrick commented
it'd be cool if a hotfix branch would fail by comparing to master, too. Chances of a hotfix including a migration are pretty high.

We should probably break this out into its own action. That way it could run when the PR gets opened & re-run whenever a commit to master gets pushed. I'll toy around a bit more!

2023-11-03 01:13 UTC, mattkrick commented
omg i don't think it's possible to trigger a workflow when the base branch gets updated https://github.com/orgs/community/discussions/64119

2023-11-10 01:04 UTC, closed without merging