fix: fix recreating invite link in case of expiration
ParabolInc/parabol pull request #9222
Opened 2023-11-20 12:54 UTC by igorlesnenko

fix #9062

I'm not exactly sure why #9062 happens.
We show dots if token is invalid, then we are fetching another token from the frontend.
I may suggest that on mobile with slow connection user may see dots for a while while we are fetching a new token.

However, this should rarely happen because if token is expired, we create new on the backend before returning it. 

This mechanism was broken. I fixed it, which possibly fixes the whole issue

**How to test:**
- Create a fresh team
- Open invite dialog, copy invitation ID from the URL for example XSDBR1S0TF0X
- Expire the url by running:

```
r.db('actionDevelopment')
  .table("MassInvitation")
 .get('XSDBR1S0TF0X')
 .update({
   expiration: new Date()
 })
```

- Refresh page, open invite dialog again, see that a new invite URL appears and you didn't see dots while it was loading

2023-11-20 12:57 UTC, igorlesnenko commented on packages/server/graphql/types/Team.ts
> -        if (newestInvitationToken?.expiration ?? new Date(0) > new Date())
this was always `false`

2023-11-21 12:30 UTC, nickoferrall approved these changes

2023-11-27 14:07 UTC, Dschoordsch requested changes
The change is fine, but does not solve the underlying problem. I could trigger the *** invite by:
* open the "Invite to Team" dialog
* stop the server
* invalidate the token
* start the server

The client reconnects but refreshes the token with ***

2024-01-10 11:30 UTC, igorlesnenko commented
@Dschoordsch not able to reproduce this, am I doing this right: https://www.loom.com/share/87e349a8d825420ebacabc5881d087ea ?

2024-01-10 12:20 UTC, Dschoordsch commented
Yes, the steps were correct, I think only the slow restart of the server messed it up: https://www.loom.com/share/428542d75b5d4be0aad2d544f9b8b0bd?sid=c859c58b-64f7-4029-878d-ba02dfc8a515

2024-01-29 08:22 UTC, igorlesnenko commented
Finally reproduced using offline mode in Network tab

2024-01-29 10:59 UTC, Dschoordsch approved these changes
Works!

2024-01-29 16:39 UTC, merged