feat(kudos): enable mentions in retro reflections
ParabolInc/parabol pull request #9284
Opened 2023-12-13 13:23 UTC by igorlesnenko

<img width="344" alt="image" src="https://github.com/ParabolInc/parabol/assets/466991/978252f5-4fd5-4256-b613-60b9095fd4ed">

2023-12-19 11:56 UTC, nickoferrall approved these changes

2023-12-19 11:56 UTC, nickoferrall commented on packages/client/components/ReflectionGroup/RemoteReflection.tsx
> +            setEditorState={() => {
+1 could this and `handleKeyDownFallback` and `placeholder` be optional props in `ReflectionEditorWrapper`?

2024-01-04 16:45 UTC, Dschoordsch requested changes
Overall looks good. The added functions, like mentions and links work. However there is something weird happening with the editor state: https://www.loom.com/share/4307debd45fb49968183f7c68f58ca94?sid=9cdf50f6-16dc-4d9c-a211-c46e7328e49a

2024-01-04 16:45 UTC, Dschoordsch commented on packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
> +                  editorRef={editorRef}
-1 this part seems wrong. If we have some cards in flight, they should not need a reference to the editor anymore as I should not be able to do any edits anymore

2024-01-10 11:07 UTC, Dschoordsch approved these changes
Works.
One thing that's missing: we're not sending any notifications for a mention in a reflection. Will this be part of the next step?

2024-01-11 03:43 UTC, igorlesnenko commented
> One thing that's missing: we're not sending any notifications for a mention in a reflection. Will this be part of the next step?

Going to work on it as a next issue: https://github.com/ParabolInc/parabol/issues/9328

2024-01-11 03:44 UTC, merged