fix: limit invites from spammers
ParabolInc/parabol pull request #9416
Opened 2024-02-09 10:30 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/9374

If the user has sent 100 or more invites and none have been accepted, prevent them from sending more invites. 

We could be stricter and set a lower limit or prevent them from sending invites even if they have more than one accepted invite if there are many unaccepted invites, but I'm more concerned about preventing real users from sending invites. 

### To test

- [ ] If there are 100 unaccepted invites, no more invites are sent

2024-02-12 10:27 UTC, Dschoordsch requested changes

2024-02-12 10:27 UTC, Dschoordsch commented on packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
> +
-1 We need to do this before we check whether or not an email is valid, otherwise this gives spammers still some utility

2024-02-14 13:17 UTC, Dschoordsch requested changes
I just tested to send 150 invites straight away and it did not complain. I think we need to check if the total + new invites would be > 100 and fail.

2024-02-26 10:36 UTC, Dschoordsch requested changes
Does not work for me:
* create a new team
* from the team dash invite >100 emails

Also we allow invites on team/org creation which are not limited right now.

2024-02-26 14:44 UTC, nickoferrall commented
Updated! Here's a Loom demo: https://www.loom.com/share/f091ff7ec2154221bf4b70a9b5b364b8

Emails won't be sent to users with 0 accepted invites and with more than 100 pending invites. If they create a team or org and there's an error sending the emails, they don't get feedback, but the emails won't be sent. You can see in the terminal that there's an error message. Not the ideal UX, but this was a design decision we originally made. 

We could make this stricter, e.g. if there are fewer than 10 accepted invites, you can't invite more than 100 people at a time, but it's probably best to be too lenient than too strict.

2024-02-26 15:47 UTC, Dschoordsch approved these changes
Works now!

2024-02-28 09:59 UTC, merged