chore: remove discussion prompt from summary
ParabolInc/parabol pull request #9711
Opened 2024-05-03 11:54 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/9710

Demo: https://www.loom.com/share/728f893c2e054fbbad82f849e89ffeaa

### To test

- [ ] Add comments to a discussion thread 
- [ ] Go to the meeting summary and see that there's an AI Summary of the discussion thread and no discussion prompt

2024-05-03 14:45 UTC, nickoferrall commented on packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
> +    if (!hasMoreThanOneReflection || organization.featureFlags.noAISummary) return null
If there's more than one reflection, we'll always create the meeting summary unless `noAISummary` is true, so we don't need to check if there's a discussion summary or reflection group summary (which is now removed anyway)

2024-05-07 13:57 UTC, Dschoordsch requested changes
Did not test yet

2024-05-07 13:57 UTC, Dschoordsch commented on packages/client/mutations/EndRetrospectiveMutation.ts
> +      const hasOpenAISummary = hasMoreThanOneReflection || !organization.featureFlags.noAISummary
-1 this should be `&&`, shouldn't it?

2024-05-07 13:57 UTC, Dschoordsch commented on packages/server/graphql/mutations/helpers/generateDiscussionPrompt.ts
> +      const [fullQuestion] = await Promise.all([
-1 No need to wrap a single call in `Promise.all([...])`

2024-05-08 07:15 UTC, Dschoordsch approved these changes

2024-05-08 10:47 UTC, merged