feat: add logic that lets users favorite a template
ParabolInc/parabol pull request #9713
Opened 2024-05-03 16:20 UTC by nickoferrall

Fix https://github.com/ParabolInc/parabol/issues/9115

Loom demo: https://www.loom.com/share/d59162967e244522aa40b73290a9c9a8

### AC

- [ ] Can favourite a template and see it show up in your favourites section
- [ ] Can un-favourite a template
- [ ] Can favourite and unfavourite a template from the template details view

2024-05-07 14:24 UTC, Dschoordsch requested changes
The heart seems a bit misaligned for me (Safari, Mac), slightly too high on the card and more so on the category. It also conflicts with the "custom" badge on master, but we could remove that one again.
<img width="817" alt="image" src="https://github.com/ParabolInc/parabol/assets/7331043/6788be18-4a39-4d1e-8351-b76ab7eb8640">

2024-05-07 14:24 UTC, Dschoordsch commented on packages/server/graphql/public/types/User.ts
> +      favoriteTemplateIds.map((templateId) => dataLoader.get('meetingTemplates').load(templateId))
-1 Why not use `dataLoader.get('meetingTemplates').loadMany(favouriteTemplateIds).filter(isValid)`?

2024-05-07 14:24 UTC, Dschoordsch commented on packages/server/dataloader/customLoaderMakers.ts
> +      return userIds.map((userId) => userIdToFavoriteTemplateIds.get(userId) || [])
+1 you could use `normalizeResults`:
```
return normalizeResults(userIds, users).map((user) => user?.favouriteTemplateIds || [])
```

2024-05-07 14:24 UTC, Dschoordsch commented on packages/server/graphql/public/typeDefs/toggleFavoriteTemplate.graphql
> +  user: User!
+1 Seems excessive to return the full user. I think it would be enough to return the updated template and favourite state.

2024-05-08 10:57 UTC, nickoferrall commented
I've moved the heart in the card to be slightly lower and to the right. For the custom label, we have a separate [discussion](https://parabol.slack.com/archives/C836NA350/p1715104125865839?thread_ts=1715094125.441169&cid=C836NA350) in Slack around that.

In the category labels, I think it is centred:

![Screenshot 2024-05-07 at 17 46 18](https://github.com/ParabolInc/parabol/assets/39854876/d01063a0-2222-45ec-9b33-4b763f6972b5)

![Screenshot 2024-05-07 at 17 44 49 (2)](https://github.com/ParabolInc/parabol/assets/39854876/ef2237e1-eaa4-417c-a475-0bc4a75871ba)

2024-05-08 14:10 UTC, Dschoordsch requested changes
I don't want to be picky, but the category heart is offset 2px to the top
<img width="811" alt="image" src="https://github.com/ParabolInc/parabol/assets/7331043/87aa1e1d-2013-4c82-b984-e08661e77c41">
<img width="811" alt="image" src="https://github.com/ParabolInc/parabol/assets/7331043/2da99f3c-c89c-4703-9d5d-caf46445862b">

We also need to do something about the custom label first before merging.

2024-05-08 17:06 UTC, nickoferrall commented
For the custom label, once you and Terry have reached a decision in the Slack [discussion](https://parabol.slack.com/archives/C836NA350/p1715176323724199?thread_ts=1715094125.441169&cid=C836NA350), I can update this PR or wait for the "Custom" label to be reverted/changed. 

> I don't want to be picky, but the category heart is offset 2px to the top

On Chrome, it was centered for me, but I can see the 2px offset on Safari. I've pushed an update and now it's centered on Safari for me, too:

<img width="267" alt="Screenshot 2024-05-08 at 18 00 38" src="https://github.com/ParabolInc/parabol/assets/39854876/8457d050-9ed2-4375-9a88-ca32d22cc7a4">

<img width="246" alt="Screenshot 2024-05-08 at 18 00 25" src="https://github.com/ParabolInc/parabol/assets/39854876/6c09e24a-661d-41c9-8940-abd926266220">

2024-05-10 07:49 UTC, Dschoordsch approved these changes

2024-05-20 18:11 UTC, merged