fix: team lead can view teams in org settings
ParabolInc/parabol pull request #9739
Opened 2024-05-08 11:53 UTC by nickoferrall

### To test

- [ ] Team lead can view the teams page even if they're not the billing lead

2024-05-08 16:20 UTC, Dschoordsch requested changes

2024-05-08 16:20 UTC, Dschoordsch commented on packages/server/graphql/types/Organization.ts
> +        return authToken.tms.some((teamId) => isTeamLead(viewerId, teamId, dataLoader))
-1 Did not test, but Array.some would call isTeamLead synchronous which would always be a truthy result (a Promise)

2024-05-09 13:46 UTC, nickoferrall commented
Updated! 

In production, only billing leads can view the Teams page. So a user that is not the billing lead but has been promoted to team lead, can't see the Teams page. 

This PR fixes that. But a user could just create a new team in the org, be team lead of that new team, and then have access to the Teams page. 

The Teams page contains email information, which is why we restricted it before:

![Screenshot 2024-05-09 at 14 37 21](https://github.com/ParabolInc/parabol/assets/39854876/1c0268d0-e443-4008-ae0a-ee5987607cd9)


Some options:
1. Keep things as they are in prod. Only billing leads can see the Teams page.
2. Use this PR. Team leads can see the Teams page, too. We know that users could join an org, create a new team, and get access to the Teams page. 
3. Use this PR, but in the Teams page, only let team leads who are not the billing lead see the teams that they are the lead of. 
4. Let everyone in the org see the Teams page.

I lean towards options 1 or 3. What do you think?

2024-05-22 12:59 UTC, Dschoordsch approved these changes

2024-05-22 13:40 UTC, merged