fix: fix the issue where a successful upgrade won't refresh the billing page
ParabolInc/parabol pull request #9740
Opened 2024-05-08 11:55 UTC by tianrunhe

# Description

Fixes/Partially Fixes #[issue number]
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

2024-05-08 14:00 UTC, Dschoordsch requested changes

2024-05-08 14:00 UTC, Dschoordsch commented on packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
> +      }
-1 let's put this logic in the `upgradeToTeamTierSuccessUpdater` where we also open the drawer and show the confetti

2024-05-10 07:25 UTC, Dschoordsch approved these changes
For me it's missing the 2 topmost sections ("Invoices" and "Credit card") after the upgrade without a manual refresh, but it's already an improvement to the state before.

2024-05-10 18:32 UTC, tianrunhe commented
> For me it's missing the 2 topmost sections ("Invoices" and "Credit card") after the upgrade without a manual refresh, but it's already an improvement to the state before.

The invoices section is a bit tricky: we need to wait for Stripe to finalize the paid invoice & create the upcoming invoice to have the data to populate that vie but those happen a little bit later than the payment success. To give the customer a faster turnaround & an indicator they have successfully upgraded, I think this is fine for now.

2024-05-10 18:33 UTC, merged